import bcrypt from "bcryptjs";
import { Prisma } from "../app/generated/prisma/client";

const BASE_TIME = new Date("2026-04-14T12:00:00.000Z");
const BCRYPT_SALT = "$2b$10$CwTycUXWue0Thq9StjUM0u";

const atHours = (deltaHours: number) =>
  new Date(BASE_TIME.getTime() + deltaHours * 60 * 60 * 1000);

const atDays = (deltaDays: number) => atHours(deltaDays * 24);

export const fixtureMeta = {
  baseTime: BASE_TIME,
  publicNowHint: "2026-04-14T12:00:00.000Z",
  ownerPlaintextPassword: "OwnerPass123!",
  shopperPlaintextPassword: "ShopperPass123!",
};

export const ids = {
  owners: {
    linh: "11111111-1111-1111-1111-111111111111",
    abdullah: "22222222-2222-2222-2222-222222222222",
    maria: "33333333-3333-3333-3333-333333333333",
    noStoreOwner: "44444444-4444-4444-4444-444444444444",
    jiyeon: "66666666-6666-6666-6666-666666666661",
    omar: "66666666-6666-6666-6666-666666666662",
    evelyn: "66666666-6666-6666-6666-666666666663",
    noStoreOwnerTwo: "66666666-6666-6666-6666-666666666664",
    pressJuice: "77777777-7777-7777-7777-777777777777",
  },
  stores: {
    lotus: "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa1",
    crescent: "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa2",
    threeRivers: "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa3",
    tokyoMart: "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa4",
    riverHalalHub: "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa5",
    eastEndOrganic: "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa6",
    pressJuice: "88888888-8888-8888-8888-888888888888",
  },
  shoppers: {
    nina: "55555555-5555-5555-5555-555555555555",
    jordan: "55555555-5555-5555-5555-555555555556",
    shopper03: "55555555-5555-5555-5555-555555555557",
    shopper04: "55555555-5555-5555-5555-555555555558",
    shopper05: "55555555-5555-5555-5555-555555555559",
    shopper06: "55555555-5555-5555-5555-555555555560",
    shopper07: "55555555-5555-5555-5555-555555555561",
    shopper08: "55555555-5555-5555-5555-555555555562",
    shopper09: "55555555-5555-5555-5555-555555555563",
    shopper10: "55555555-5555-5555-5555-555555555564",
    shopper11: "55555555-5555-5555-5555-555555555565",
    shopper12: "55555555-5555-5555-5555-555555555566",
  },
  items: {
    bokChoy: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb1",
    bokChoiTypo: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb2",
    halalLambShoulder: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb3",
    spinach: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb4",
    oatMilk: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb5",
    ramen: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb6",
    cilantro: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb7",
    napaCabbage: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb8",
    gochujang: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb9",
    halalChickenThighs: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbb10",
    datesMedjool: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbb11",
    kale: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbb12",
    sourdough: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbb13",
    tomatoeSauceTypo: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbb14",
    pressJuice64oz: "99999999-9999-9999-9999-999999999991",
    pressHoneycrispCider: "99999999-9999-9999-9999-999999999992",
  },
  freshUpdates: {
    lotusRecent: "cccccccc-cccc-cccc-cccc-ccccccccccc1",
    crescentRecent: "cccccccc-cccc-cccc-cccc-ccccccccccc2",
    threeRiversStale: "cccccccc-cccc-cccc-cccc-ccccccccccc3",
    lotusSoftDeleted: "cccccccc-cccc-cccc-cccc-ccccccccccc4",
    tokyoRecent: "cccccccc-cccc-cccc-cccc-ccccccccccc5",
    riverHalalRecent: "cccccccc-cccc-cccc-cccc-ccccccccccc6",
    eastEndStale: "cccccccc-cccc-cccc-cccc-ccccccccccc7",
    tokyoSoftDeleted: "cccccccc-cccc-cccc-cccc-ccccccccccc8",
    pressRecentJuice: "cccccccc-cccc-cccc-cccc-cccccccccc01",
    pressRecentCider: "cccccccc-cccc-cccc-cccc-cccccccccc02",
    pressOrganicNote: "cccccccc-cccc-cccc-cccc-cccccccccc03",
  },
  deals: {
    lotusActive: "dddddddd-dddd-dddd-dddd-ddddddddddd1",
    lotusExpiringSoon: "dddddddd-dddd-dddd-dddd-ddddddddddd2",
    crescentExpired: "dddddddd-dddd-dddd-dddd-ddddddddddd3",
    crescentHistorical: "dddddddd-dddd-dddd-dddd-ddddddddddd4",
    crescentReusedActive: "dddddddd-dddd-dddd-dddd-ddddddddddd5",
    threeRiversSoftDeleted: "dddddddd-dddd-dddd-dddd-ddddddddddd6",
    tokyoActive: "dddddddd-dddd-dddd-dddd-ddddddddddd7",
    tokyoExpiringSoon: "dddddddd-dddd-dddd-dddd-ddddddddddd8",
    riverHalalExpired: "dddddddd-dddd-dddd-dddd-ddddddddddd9",
    eastEndHistorical: "dddddddd-dddd-dddd-dddd-dddddddddd10",
    eastEndReusedActive: "dddddddd-dddd-dddd-dddd-dddddddddd11",
    riverHalalSoftDeleted: "dddddddd-dddd-dddd-dddd-dddddddddd12",
    pressWeekendGallon: "dddddddd-dddd-dddd-dddd-dddddddddd13",
    pressCider2for1: "dddddddd-dddd-dddd-dddd-dddddddddd14",
  },
  alerts: {
    ninaStoreFollowLotus: "eeeeeeee-eeee-eeee-eeee-eeeeeeeeeee1",
    ninaItemRestockLamb: "eeeeeeee-eeee-eeee-eeee-eeeeeeeeeee2",
    jordanStoreFollowTokyo: "eeeeeeee-eeee-eeee-eeee-eeeeeeeeeee3",
    jordanItemRestockKale: "eeeeeeee-eeee-eeee-eeee-eeeeeeeeeee4",
  },
  ratings: {
    ninaLotus: "ffffffff-ffff-ffff-ffff-fffffffffff1",
    ninaCrescent: "ffffffff-ffff-ffff-ffff-fffffffffff2",
    jordanTokyo: "ffffffff-ffff-ffff-ffff-fffffffffff3",
    jordanEastEnd: "ffffffff-ffff-ffff-ffff-fffffffffff4",
    alexThreeRivers: "ffffffff-ffff-ffff-ffff-fffffffffff5",
    taylorRiverHalal: "ffffffff-ffff-ffff-ffff-fffffffffff6",
    samLotus: "ffffffff-ffff-ffff-ffff-fffffffffff7",
    morganEastEnd: "ffffffff-ffff-ffff-ffff-fffffffffff8",
  },
} as const;

export const owners = [
  {
    id: ids.owners.linh,
    email: "linh.tran@gmail.com",
    name: "Linh Tran",
    passwordHash: bcrypt.hashSync(fixtureMeta.ownerPlaintextPassword, BCRYPT_SALT),
    createdAt: atDays(-45),
  },
  {
    id: ids.owners.abdullah,
    email: "akhan.halal@gmail.com",
    name: "Abdullah Khan",
    passwordHash: bcrypt.hashSync(fixtureMeta.ownerPlaintextPassword, BCRYPT_SALT),
    createdAt: atDays(-30),
  },
  {
    id: ids.owners.maria,
    email: "msantos.organic@gmail.com",
    name: "Maria Santos",
    passwordHash: bcrypt.hashSync(fixtureMeta.ownerPlaintextPassword, BCRYPT_SALT),
    createdAt: atDays(-25),
  },
  {
    id: ids.owners.noStoreOwner,
    email: "casey.morris@outlook.com",
    name: "Casey Morris",
    passwordHash: bcrypt.hashSync(fixtureMeta.ownerPlaintextPassword, BCRYPT_SALT),
    createdAt: atDays(-3),
  },
  {
    id: ids.owners.jiyeon,
    email: "jpark.pgh@gmail.com",
    name: "Jiyeon Park",
    passwordHash: bcrypt.hashSync(fixtureMeta.ownerPlaintextPassword, BCRYPT_SALT),
    createdAt: atDays(-22),
  },
  {
    id: ids.owners.omar,
    email: "ohassan.market@gmail.com",
    name: "Omar Hassan",
    passwordHash: bcrypt.hashSync(fixtureMeta.ownerPlaintextPassword, BCRYPT_SALT),
    createdAt: atDays(-18),
  },
  {
    id: ids.owners.evelyn,
    email: "evelyn.brooks@gmail.com",
    name: "Evelyn Brooks",
    passwordHash: bcrypt.hashSync(fixtureMeta.ownerPlaintextPassword, BCRYPT_SALT),
    createdAt: atDays(-16),
  },
  {
    id: ids.owners.noStoreOwnerTwo,
    email: "robin.kim@outlook.com",
    name: "Robin Kim",
    passwordHash: bcrypt.hashSync(fixtureMeta.ownerPlaintextPassword, BCRYPT_SALT),
    createdAt: atDays(-2),
  },
  {
    id: ids.owners.pressJuice,
    email: "m.webb.pgh@gmail.com",
    name: "Marcus Webb",
    passwordHash: bcrypt.hashSync(fixtureMeta.ownerPlaintextPassword, BCRYPT_SALT),
    createdAt: atDays(-14),
  },
];

export const stores = [
  {
    id: ids.stores.lotus,
    ownerId: ids.owners.linh,
    name: "Lotus Asian Market",
    address: "5899 Forbes Ave, Pittsburgh, PA 15217",
    lat: 40.43734,
    lng: -79.92148,
    categories: ["asian", "produce"],
    isPublished: true,
    createdAt: atDays(-40),
    hours: { open: "09:00", close: "20:00" },
  },
  {
    id: ids.stores.crescent,
    ownerId: ids.owners.abdullah,
    name: "Crescent Halal Grocer",
    address: "202 Brownsville Rd, Pittsburgh, PA 15210",
    lat: 40.40502,
    lng: -79.98631,
    categories: ["halal", "ebt"],
    isPublished: true,
    createdAt: atDays(-28),
    hours: { open: "08:00", close: "22:00" },
  },
  {
    id: ids.stores.threeRivers,
    ownerId: ids.owners.maria,
    name: "Three Rivers Organic Produce",
    address: "2401 Smallman St, Pittsburgh, PA 15222",
    lat: 40.45258,
    lng: -79.97938,
    categories: ["organic", "produce", "ebt"],
    isPublished: true,
    createdAt: atDays(-20),
    hours: { open: "07:00", close: "18:00" },
  },
  {
    id: ids.stores.tokyoMart,
    ownerId: ids.owners.jiyeon,
    name: "Tokyo Mart Shadyside",
    address: "5525 Walnut St, Pittsburgh, PA 15232",
    lat: 40.45131,
    lng: -79.9345,
    categories: ["asian", "ebt"],
    isPublished: true,
    createdAt: atDays(-18),
    hours: { open: "10:00", close: "21:00" },
  },
  {
    id: ids.stores.riverHalalHub,
    ownerId: ids.owners.omar,
    name: "River Halal Hub",
    address: "3115 Banksville Rd, Pittsburgh, PA 15216",
    lat: 40.41403,
    lng: -80.03962,
    categories: ["halal", "produce"],
    isPublished: true,
    createdAt: atDays(-15),
    hours: { open: "08:00", close: "21:00" },
  },
  {
    id: ids.stores.eastEndOrganic,
    ownerId: ids.owners.evelyn,
    name: "East End Organic Pantry",
    address: "6400 Penn Ave, Pittsburgh, PA 15206",
    lat: 40.4609,
    lng: -79.91922,
    categories: ["organic", "produce", "ebt"],
    isPublished: true,
    createdAt: atDays(-12),
    hours: { open: "09:00", close: "19:00" },
  },
  {
    id: ids.stores.pressJuice,
    ownerId: ids.owners.pressJuice,
    name: "The Press Juice Co.",
    address: "5883 Wilkins Ave, Pittsburgh, PA 15217",
    lat: 40.4372,
    lng: -79.9148,
    categories: ["organic", "produce"],
    isPublished: true,
    createdAt: atDays(-12),
    hours: { open: "08:00", close: "18:00" },
  },
];

const shopperPasswordHash = bcrypt.hashSync(
  fixtureMeta.shopperPlaintextPassword,
  BCRYPT_SALT,
);

export const shoppers = [
  {
    id: ids.shoppers.nina,
    email: "nina.patel@gmail.com",
    name: "Nina Patel",
    passwordHash: shopperPasswordHash,
    createdAt: atDays(-10),
  },
  {
    id: ids.shoppers.jordan,
    email: "j.chen.pgh@gmail.com",
    name: "Jordan Chen",
    passwordHash: shopperPasswordHash,
    createdAt: atDays(-8),
  },
  {
    id: ids.shoppers.shopper03,
    email: "alex.martinez@gmail.com",
    name: "Alex Martinez",
    passwordHash: shopperPasswordHash,
    createdAt: atDays(-7),
  },
  {
    id: ids.shoppers.shopper04,
    email: "t.williams@outlook.com",
    name: "Taylor Williams",
    passwordHash: shopperPasswordHash,
    createdAt: atDays(-6),
  },
  {
    id: ids.shoppers.shopper05,
    email: "sam.rodriguez@gmail.com",
    name: "Sam Rodriguez",
    passwordHash: shopperPasswordHash,
    createdAt: atDays(-6),
  },
  {
    id: ids.shoppers.shopper06,
    email: "riley.thompson@gmail.com",
    name: "Riley Thompson",
    passwordHash: shopperPasswordHash,
    createdAt: atDays(-5),
  },
  {
    id: ids.shoppers.shopper07,
    email: "morgan.lee@yahoo.com",
    name: "Morgan Lee",
    passwordHash: shopperPasswordHash,
    createdAt: atDays(-5),
  },
  {
    id: ids.shoppers.shopper08,
    email: "jamiedavis@gmail.com",
    name: "Jamie Davis",
    passwordHash: shopperPasswordHash,
    createdAt: atDays(-4),
  },
  {
    id: ids.shoppers.shopper09,
    email: "d.anderson.pgh@gmail.com",
    name: "Drew Anderson",
    passwordHash: shopperPasswordHash,
    createdAt: atDays(-4),
  },
  {
    id: ids.shoppers.shopper10,
    email: "caseynguyen@gmail.com",
    name: "Casey Nguyen",
    passwordHash: shopperPasswordHash,
    createdAt: atDays(-3),
  },
  {
    id: ids.shoppers.shopper11,
    email: "cam.foster@gmail.com",
    name: "Cameron Foster",
    passwordHash: shopperPasswordHash,
    createdAt: atDays(-3),
  },
  {
    id: ids.shoppers.shopper12,
    email: "peyton.clark@outlook.com",
    name: "Peyton Clark",
    passwordHash: shopperPasswordHash,
    createdAt: atDays(-2),
  },
];

export const items = [
  {
    id: ids.items.bokChoy,
    storeId: ids.stores.lotus,
    name: "Baby Bok Choy",
    description: "Tender green heads from regional growers, great for stir-fries and soups",
    inStock: true,
    lastUpdated: atHours(-3),
  },
  {
    id: ids.items.bokChoiTypo,
    storeId: ids.stores.lotus,
    name: "Bok Choi Family Pack",
    description: "Large heads, ideal for kimchi or braised dishes",
    inStock: false,
    lastUpdated: atDays(-2),
  },
  {
    id: ids.items.ramen,
    storeId: ids.stores.lotus,
    name: "Shin Ramyun 4-Pack",
    description: "Spicy instant noodle multipack — a pantry staple",
    inStock: true,
    lastUpdated: atHours(-6),
  },
  {
    id: ids.items.halalLambShoulder,
    storeId: ids.stores.crescent,
    name: "Halal Lamb Shoulder",
    description: "Fresh halal-certified lamb shoulder, cut to order on request",
    inStock: true,
    lastUpdated: atHours(-2),
  },
  {
    id: ids.items.cilantro,
    storeId: ids.stores.crescent,
    name: "Cillantro Bunch",
    description: "Fresh herb bunches, great for salsa, curries, and garnishes",
    inStock: true,
    lastUpdated: atHours(-5),
  },
  {
    id: ids.items.spinach,
    storeId: ids.stores.threeRivers,
    name: "Organic Spinach",
    description: "Certified organic from local farms, sold in loose bunches",
    inStock: false,
    lastUpdated: atDays(-4),
  },
  {
    id: ids.items.oatMilk,
    storeId: ids.stores.threeRivers,
    name: "Oat Milk Unsweetened",
    description: "Barista blend, unsweetened — works great in coffee",
    inStock: true,
    lastUpdated: atHours(-7),
  },
  {
    id: ids.items.napaCabbage,
    storeId: ids.stores.tokyoMart,
    name: "Napa Cabbage",
    description: "Fresh whole heads, perfect for kimchi or hot pot",
    inStock: true,
    lastUpdated: atHours(-4),
  },
  {
    id: ids.items.gochujang,
    storeId: ids.stores.tokyoMart,
    name: "Gochujang Paste",
    description: "Traditional Korean chili paste, medium heat",
    inStock: true,
    lastUpdated: atHours(-9),
  },
  {
    id: ids.items.halalChickenThighs,
    storeId: ids.stores.riverHalalHub,
    name: "Halal Chicken Thighs",
    description: "Bone-in halal chicken thighs, fresh daily",
    inStock: false,
    lastUpdated: atDays(-1),
  },
  {
    id: ids.items.datesMedjool,
    storeId: ids.stores.riverHalalHub,
    name: "Medjool Dates",
    description: "Large premium dates imported from the Jordan Valley",
    inStock: true,
    lastUpdated: atHours(-11),
  },
  {
    id: ids.items.kale,
    storeId: ids.stores.eastEndOrganic,
    name: "Organic Kale",
    description: "Locally grown curly kale, harvested within 48 hours of delivery",
    inStock: true,
    lastUpdated: atHours(-13),
  },
  {
    id: ids.items.sourdough,
    storeId: ids.stores.eastEndOrganic,
    name: "Whole Grain Sourdough",
    description: "Stone-milled whole grain loaf from a local Pittsburgh bakery",
    inStock: true,
    lastUpdated: atHours(-15),
  },
  {
    id: ids.items.tomatoeSauceTypo,
    storeId: ids.stores.eastEndOrganic,
    name: "Tomatoe Sauce",
    description: "Slow-cooked marinara with heirloom tomatoes and fresh basil",
    inStock: false,
    lastUpdated: atDays(-3),
  },
  {
    id: ids.items.pressJuice64oz,
    storeId: ids.stores.pressJuice,
    name: "Fresh Pressed Apple Juice 64oz",
    description: "Cold-pressed from local Pennsylvania apples, no added sugar",
    inStock: true,
    lastUpdated: atHours(-5),
  },
  {
    id: ids.items.pressHoneycrispCider,
    storeId: ids.stores.pressJuice,
    name: "Honeycrisp Apple Cider",
    description: "Small-batch seasonal cider, slightly sweet with no preservatives",
    inStock: true,
    lastUpdated: atHours(-8),
  },
];

export const freshUpdates = [
  {
    id: ids.freshUpdates.lotusRecent,
    storeId: ids.stores.lotus,
    itemId: ids.items.bokChoy,
    itemName: "Baby Bok Choy",
    note: "Fresh delivery arrived this morning — very crisp today.",
    createdAt: atHours(-8),
    deletedAt: null,
  },
  {
    id: ids.freshUpdates.crescentRecent,
    storeId: ids.stores.crescent,
    itemId: ids.items.halalLambShoulder,
    itemName: "Halal Lamb Shoulder",
    note: "Halal-certified cuts available today, freshly butchered.",
    createdAt: atHours(-20),
    deletedAt: null,
  },
  {
    id: ids.freshUpdates.threeRiversStale,
    storeId: ids.stores.threeRivers,
    itemId: ids.items.spinach,
    itemName: "Organic Spinach",
    note: "Restocked Tuesday from our local farm partner — call ahead if you need a large quantity.",
    createdAt: atDays(-4),
    deletedAt: null,
  },
  {
    id: ids.freshUpdates.lotusSoftDeleted,
    storeId: ids.stores.lotus,
    itemId: ids.items.bokChoiTypo,
    itemName: "Bok Choi Family Pack",
    note: "Sold out faster than expected — removing this post to avoid confusion.",
    createdAt: atHours(-22),
    deletedAt: atHours(-2),
  },
  {
    id: ids.freshUpdates.tokyoRecent,
    storeId: ids.stores.tokyoMart,
    itemId: ids.items.napaCabbage,
    itemName: "Napa Cabbage",
    note: "Fresh heads in from this morning's shipment — come early for best selection.",
    createdAt: atHours(-6),
    deletedAt: null,
  },
  {
    id: ids.freshUpdates.riverHalalRecent,
    storeId: ids.stores.riverHalalHub,
    itemId: ids.items.datesMedjool,
    itemName: "Medjool Dates",
    note: "New batch arrived at opening — perfectly ripe.",
    createdAt: atHours(-14),
    deletedAt: null,
  },
  {
    id: ids.freshUpdates.eastEndStale,
    storeId: ids.stores.eastEndOrganic,
    itemId: ids.items.tomatoeSauceTypo,
    itemName: "Tomatoe Sauce",
    note: "Small batch came in earlier this week — a few jars still available.",
    createdAt: atDays(-5),
    deletedAt: null,
  },
  {
    id: ids.freshUpdates.tokyoSoftDeleted,
    storeId: ids.stores.tokyoMart,
    itemId: ids.items.gochujang,
    itemName: "Gochujang Paste",
    note: "Removing this — we had more in the back than I thought. Still well stocked!",
    createdAt: atHours(-25),
    deletedAt: atHours(-4),
  },
  {
    id: ids.freshUpdates.pressRecentJuice,
    storeId: ids.stores.pressJuice,
    itemId: ids.items.pressJuice64oz,
    itemName: "Fresh Pressed Apple Juice 64oz",
    note: "New pressing today — crisp and sweet, picked up this morning.",
    createdAt: atHours(-6),
    deletedAt: null,
  },
  {
    id: ids.freshUpdates.pressRecentCider,
    storeId: ids.stores.pressJuice,
    itemId: ids.items.pressHoneycrispCider,
    itemName: "Honeycrisp Apple Cider",
    note: "Back in stock for the weekend — limited bottles.",
    createdAt: atHours(-18),
    deletedAt: null,
  },
  {
    id: ids.freshUpdates.pressOrganicNote,
    storeId: ids.stores.pressJuice,
    itemId: ids.items.pressJuice64oz,
    itemName: "Fresh Pressed Apple Juice 64oz",
    note: "This week's run uses certified organic apples — limited quantity.",
    createdAt: atHours(-42),
    deletedAt: null,
  },
];

export const deals = [
  {
    id: ids.deals.lotusActive,
    storeId: ids.stores.lotus,
    itemId: ids.items.ramen,
    sourceDealId: null,
    title: "Shin Ramyun buy 3 get 1 free",
    description: "Stock up on your favorite spicy noodles — great value for pantry staples.",
    price: new Prisma.Decimal("4.99"),
    discountPct: 25,
    expiresAt: atDays(3),
    isExpired: false,
    createdAt: atHours(-30),
    deletedAt: null,
  },
  {
    id: ids.deals.lotusExpiringSoon,
    storeId: ids.stores.lotus,
    itemId: ids.items.bokChoy,
    sourceDealId: null,
    title: "20% off Baby Bok Choy",
    description: "Fresh-cut bundles going fast — price drop ends tonight.",
    price: new Prisma.Decimal("2.49"),
    discountPct: 20,
    expiresAt: atHours(12),
    isExpired: false,
    createdAt: atHours(-12),
    deletedAt: null,
  },
  {
    id: ids.deals.crescentExpired,
    storeId: ids.stores.crescent,
    itemId: ids.items.halalLambShoulder,
    sourceDealId: null,
    title: "30% off lamb shoulder",
    description: "Weekend halal special on fresh lamb shoulder cuts.",
    price: new Prisma.Decimal("12.99"),
    discountPct: 30,
    expiresAt: atHours(-6),
    isExpired: true,
    createdAt: atDays(-4),
    deletedAt: null,
  },
  {
    id: ids.deals.crescentHistorical,
    storeId: ids.stores.crescent,
    itemId: ids.items.halalLambShoulder,
    sourceDealId: null,
    title: "Lamb shoulder monthly special",
    description: "Last month's regular halal butcher promotion.",
    price: new Prisma.Decimal("11.49"),
    discountPct: 15,
    expiresAt: atDays(-7),
    isExpired: true,
    createdAt: atDays(-14),
    deletedAt: null,
  },
  {
    id: ids.deals.crescentReusedActive,
    storeId: ids.stores.crescent,
    itemId: ids.items.halalLambShoulder,
    sourceDealId: ids.deals.crescentHistorical,
    title: "Lamb shoulder special — back this week",
    description: "Back by popular request — same great price as last month.",
    price: new Prisma.Decimal("11.49"),
    discountPct: 15,
    expiresAt: atDays(2),
    isExpired: false,
    createdAt: atHours(-1),
    deletedAt: null,
  },
  {
    id: ids.deals.threeRiversSoftDeleted,
    storeId: ids.stores.threeRivers,
    itemId: ids.items.oatMilk,
    sourceDealId: null,
    title: "Oat milk flash sale",
    description: "Weekend sale on our most popular dairy-free staple.",
    price: new Prisma.Decimal("3.29"),
    discountPct: 10,
    expiresAt: atDays(1),
    isExpired: false,
    createdAt: atHours(-10),
    deletedAt: atHours(-3),
  },
  {
    id: ids.deals.tokyoActive,
    storeId: ids.stores.tokyoMart,
    itemId: ids.items.gochujang,
    sourceDealId: null,
    title: "15% off Gochujang",
    description: "Stock up your pantry — sale price this week only.",
    price: new Prisma.Decimal("5.49"),
    discountPct: 15,
    expiresAt: atDays(4),
    isExpired: false,
    createdAt: atHours(-18),
    deletedAt: null,
  },
  {
    id: ids.deals.tokyoExpiringSoon,
    storeId: ids.stores.tokyoMart,
    itemId: ids.items.napaCabbage,
    sourceDealId: null,
    title: "Napa cabbage 2-for-1",
    description: "Buy two heads, pay for one — tonight only.",
    price: new Prisma.Decimal("1.99"),
    discountPct: null,
    expiresAt: atHours(8),
    isExpired: false,
    createdAt: atHours(-7),
    deletedAt: null,
  },
  {
    id: ids.deals.riverHalalExpired,
    storeId: ids.stores.riverHalalHub,
    itemId: ids.items.halalChickenThighs,
    sourceDealId: null,
    title: "25% off halal chicken thighs",
    description: "Eid Mubarak special — fresh halal cuts at a community discount.",
    price: new Prisma.Decimal("6.99"),
    discountPct: 25,
    expiresAt: atHours(-20),
    isExpired: true,
    createdAt: atDays(-3),
    deletedAt: null,
  },
  {
    id: ids.deals.eastEndHistorical,
    storeId: ids.stores.eastEndOrganic,
    itemId: ids.items.kale,
    sourceDealId: null,
    title: "Organic greens bundle",
    description: "Mixed kale and spinach bundles at spring season pricing.",
    price: new Prisma.Decimal("7.99"),
    discountPct: 18,
    expiresAt: atDays(-10),
    isExpired: true,
    createdAt: atDays(-17),
    deletedAt: null,
  },
  {
    id: ids.deals.eastEndReusedActive,
    storeId: ids.stores.eastEndOrganic,
    itemId: ids.items.kale,
    sourceDealId: ids.deals.eastEndHistorical,
    title: "Organic greens bundle — spring restock",
    description: "Back for the season — same bundle at the same popular price.",
    price: new Prisma.Decimal("7.99"),
    discountPct: 18,
    expiresAt: atDays(5),
    isExpired: false,
    createdAt: atHours(-2),
    deletedAt: null,
  },
  {
    id: ids.deals.riverHalalSoftDeleted,
    storeId: ids.stores.riverHalalHub,
    itemId: ids.items.datesMedjool,
    sourceDealId: null,
    title: "Medjool dates Ramadan special",
    description: "Special pricing on premium imported dates through the weekend.",
    price: new Prisma.Decimal("8.49"),
    discountPct: 12,
    expiresAt: atDays(2),
    isExpired: false,
    createdAt: atHours(-16),
    deletedAt: atHours(-6),
  },
  {
    id: ids.deals.pressWeekendGallon,
    storeId: ids.stores.pressJuice,
    itemId: ids.items.pressJuice64oz,
    sourceDealId: null,
    title: "$1 off 64oz jugs this weekend",
    description: "Fresh pressed and bottled this morning — ends Sunday night.",
    price: new Prisma.Decimal("7.99"),
    discountPct: 11,
    expiresAt: atDays(4),
    isExpired: false,
    createdAt: atHours(-20),
    deletedAt: null,
  },
  {
    id: ids.deals.pressCider2for1,
    storeId: ids.stores.pressJuice,
    itemId: ids.items.pressHoneycrispCider,
    sourceDealId: null,
    title: "Honeycrisp cider 2 for 1",
    description: "Mix and match with any 32oz bottle while supplies last.",
    price: new Prisma.Decimal("5.49"),
    discountPct: 50,
    expiresAt: atHours(36),
    isExpired: false,
    createdAt: atHours(-8),
    deletedAt: null,
  },
];

export const alerts = [
  {
    id: ids.alerts.ninaStoreFollowLotus,
    shopperId: ids.shoppers.nina,
    storeId: ids.stores.lotus,
    itemId: null,
    type: "store_follow" as const,
    isActive: true,
    createdAt: atDays(-1),
  },
  {
    id: ids.alerts.ninaItemRestockLamb,
    shopperId: ids.shoppers.nina,
    storeId: ids.stores.crescent,
    itemId: ids.items.halalLambShoulder,
    type: "item_restock" as const,
    isActive: true,
    createdAt: atHours(-5),
  },
  {
    id: ids.alerts.jordanStoreFollowTokyo,
    shopperId: ids.shoppers.jordan,
    storeId: ids.stores.tokyoMart,
    itemId: null,
    type: "store_follow" as const,
    isActive: true,
    createdAt: atHours(-9),
  },
  {
    id: ids.alerts.jordanItemRestockKale,
    shopperId: ids.shoppers.jordan,
    storeId: ids.stores.eastEndOrganic,
    itemId: ids.items.kale,
    type: "item_restock" as const,
    isActive: true,
    createdAt: atHours(-4),
  },
];

export const storeRatings = [
  {
    id: ids.ratings.ninaLotus,
    storeId: ids.stores.lotus,
    shopperId: ids.shoppers.nina,
    score: 5,
    note: "Great selection of fresh produce and a really friendly team. The bok choy is always crisp.",
    createdAt: atDays(-3),
    updatedAt: atDays(-3),
  },
  {
    id: ids.ratings.ninaCrescent,
    storeId: ids.stores.crescent,
    shopperId: ids.shoppers.nina,
    score: 4,
    note: "Best halal meat selection I've found in the South Side area. Fair prices.",
    createdAt: atDays(-2),
    updatedAt: atDays(-2),
  },
  {
    id: ids.ratings.jordanTokyo,
    storeId: ids.stores.tokyoMart,
    shopperId: ids.shoppers.jordan,
    score: 5,
    note: "Best spot in Pittsburgh for Korean and Japanese pantry staples. Always well-stocked.",
    createdAt: atDays(-4),
    updatedAt: atDays(-4),
  },
  {
    id: ids.ratings.jordanEastEnd,
    storeId: ids.stores.eastEndOrganic,
    shopperId: ids.shoppers.jordan,
    score: 4,
    note: "Love the sourdough and the local produce. Parking can be tricky on weekends.",
    createdAt: atDays(-3),
    updatedAt: atDays(-3),
  },
  {
    id: ids.ratings.alexThreeRivers,
    storeId: ids.stores.threeRivers,
    shopperId: ids.shoppers.shopper03,
    score: 5,
    note: "Excellent organic selection, everything feels genuinely farm-fresh.",
    createdAt: atDays(-5),
    updatedAt: atDays(-5),
  },
  {
    id: ids.ratings.taylorRiverHalal,
    storeId: ids.stores.riverHalalHub,
    shopperId: ids.shoppers.shopper04,
    score: 4,
    note: "Good variety of halal meats and the dates are always top quality.",
    createdAt: atDays(-2),
    updatedAt: atDays(-2),
  },
  {
    id: ids.ratings.samLotus,
    storeId: ids.stores.lotus,
    shopperId: ids.shoppers.shopper05,
    score: 4,
    note: "Fresh vegetables and a great Asian pantry section. Wish they were open a bit later.",
    createdAt: atDays(-6),
    updatedAt: atDays(-6),
  },
  {
    id: ids.ratings.morganEastEnd,
    storeId: ids.stores.eastEndOrganic,
    shopperId: ids.shoppers.shopper07,
    score: 5,
    note: "My go-to for organic staples in East Liberty. The kale is always harvested fresh.",
    createdAt: atDays(-1),
    updatedAt: atDays(-1),
  },
];

const PRESS_SEARCH_QUERIES = [
  "apple",
  "apple juice",
  "juice",
  "cider",
  "gallon",
  "organic",
  "honeycrisp",
  "press",
];

const LOTUS_SEARCH_QUERIES = [
  "bok choy",
  "ramen",
  "noodles",
  "spinach",
  "bok choi",
];

const TOKYO_SEARCH_QUERIES = [
  "gochujang",
  "napa cabbage",
  "kimchi",
  "korean chili",
  "miso",
];

export const storeProfileViewsSeed = [
  ...Array.from({ length: 25 }, (_, i) => ({
    storeId: ids.stores.lotus,
    createdAt: atHours(-i * 22 - 2),
  })),
  ...Array.from({ length: 20 }, (_, i) => ({
    storeId: ids.stores.crescent,
    createdAt: atHours(-i * 27 - 3),
  })),
  ...Array.from({ length: 17 }, (_, i) => ({
    storeId: ids.stores.threeRivers,
    createdAt: atHours(-i * 31 - 7),
  })),
  ...Array.from({ length: 22 }, (_, i) => ({
    storeId: ids.stores.tokyoMart,
    createdAt: atHours(-i * 25 - 5),
  })),
  ...Array.from({ length: 14 }, (_, i) => ({
    storeId: ids.stores.riverHalalHub,
    createdAt: atHours(-i * 37 - 4),
  })),
  ...Array.from({ length: 19 }, (_, i) => ({
    storeId: ids.stores.eastEndOrganic,
    createdAt: atHours(-i * 29 - 6),
  })),
  ...Array.from({ length: 38 }, (_, i) => ({
    storeId: ids.stores.pressJuice,
    createdAt: atHours(-i * 19 - 1),
  })),
];

export const storeItemSearchesSeed = [
  ...Array.from({ length: 22 }, (_, i) => ({
    storeId: ids.stores.pressJuice,
    query: PRESS_SEARCH_QUERIES[i % PRESS_SEARCH_QUERIES.length],
    createdAt: atHours(-i * 31 - 4),
  })),
  ...Array.from({ length: 12 }, (_, i) => ({
    storeId: ids.stores.lotus,
    query: LOTUS_SEARCH_QUERIES[i % LOTUS_SEARCH_QUERIES.length],
    createdAt: atHours(-i * 41 - 6),
  })),
  ...Array.from({ length: 10 }, (_, i) => ({
    storeId: ids.stores.tokyoMart,
    query: TOKYO_SEARCH_QUERIES[i % TOKYO_SEARCH_QUERIES.length],
    createdAt: atHours(-i * 47 - 8),
  })),
];
