import bcrypt from "bcryptjs";
import { Prisma } from "../app/generated/prisma/client";

const BASE_TIME = new Date("2026-04-14T12:00:00.000Z");
const BCRYPT_SALT = "$2b$10$CwTycUXWue0Thq9StjUM0u";

const atHours = (deltaHours: number) =>
  new Date(BASE_TIME.getTime() + deltaHours * 60 * 60 * 1000);

const atDays = (deltaDays: number) => atHours(deltaDays * 24);

export const fixtureMeta = {
  baseTime: BASE_TIME,
  publicNowHint: "2026-04-14T12:00:00.000Z",
  ownerPlaintextPassword: "OwnerPass123!",
  shopperPlaintextPassword: "ShopperPass123!",
};

export const ids = {
  owners: {
    linh: "11111111-1111-1111-1111-111111111111",
    abdullah: "22222222-2222-2222-2222-222222222222",
    maria: "33333333-3333-3333-3333-333333333333",
    noStoreOwner: "44444444-4444-4444-4444-444444444444",
    jiyeon: "66666666-6666-6666-6666-666666666661",
    omar: "66666666-6666-6666-6666-666666666662",
    evelyn: "66666666-6666-6666-6666-666666666663",
    noStoreOwnerTwo: "66666666-6666-6666-6666-666666666664",
    /** Demo account: matches common local-dev login for dashboard screenshots */
    ryanAppleJuice: "77777777-7777-7777-7777-777777777777",
  },
  stores: {
    lotus: "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa1",
    crescent: "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa2",
    threeRivers: "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa3",
    tokyoMart: "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa4",
    riverHalalHub: "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa5",
    eastEndOrganic: "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa6",
    ryanAppleJuice: "88888888-8888-8888-8888-888888888888",
  },
  shoppers: {
    nina: "55555555-5555-5555-5555-555555555555",
    jordan: "55555555-5555-5555-5555-555555555556",
    shopper03: "55555555-5555-5555-5555-555555555557",
    shopper04: "55555555-5555-5555-5555-555555555558",
    shopper05: "55555555-5555-5555-5555-555555555559",
    shopper06: "55555555-5555-5555-5555-555555555560",
    shopper07: "55555555-5555-5555-5555-555555555561",
    shopper08: "55555555-5555-5555-5555-555555555562",
    shopper09: "55555555-5555-5555-5555-555555555563",
    shopper10: "55555555-5555-5555-5555-555555555564",
    shopper11: "55555555-5555-5555-5555-555555555565",
    shopper12: "55555555-5555-5555-5555-555555555566",
  },
  items: {
    bokChoy: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb1",
    bokChoiTypo: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb2",
    halalLambShoulder: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb3",
    spinach: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb4",
    oatMilk: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb5",
    ramen: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb6",
    cilantro: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb7",
    napaCabbage: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb8",
    gochujang: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb9",
    halalChickenThighs: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbb10",
    datesMedjool: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbb11",
    kale: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbb12",
    sourdough: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbb13",
    tomatoeSauceTypo: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbb14",
    ryanJuice64oz: "99999999-9999-9999-9999-999999999991",
    ryanHoneycrispCider: "99999999-9999-9999-9999-999999999992",
  },
  freshUpdates: {
    lotusRecent: "cccccccc-cccc-cccc-cccc-ccccccccccc1",
    crescentRecent: "cccccccc-cccc-cccc-cccc-ccccccccccc2",
    threeRiversStale: "cccccccc-cccc-cccc-cccc-ccccccccccc3",
    lotusSoftDeleted: "cccccccc-cccc-cccc-cccc-ccccccccccc4",
    tokyoRecent: "cccccccc-cccc-cccc-cccc-ccccccccccc5",
    riverHalalRecent: "cccccccc-cccc-cccc-cccc-ccccccccccc6",
    eastEndStale: "cccccccc-cccc-cccc-cccc-ccccccccccc7",
    tokyoSoftDeleted: "cccccccc-cccc-cccc-cccc-ccccccccccc8",
    ryanRecentJuice: "cccccccc-cccc-cccc-cccc-cccccccccc01",
    ryanRecentCider: "cccccccc-cccc-cccc-cccc-cccccccccc02",
    ryanOrganicNote: "cccccccc-cccc-cccc-cccc-cccccccccc03",
  },
  deals: {
    lotusActive: "dddddddd-dddd-dddd-dddd-ddddddddddd1",
    lotusExpiringSoon: "dddddddd-dddd-dddd-dddd-ddddddddddd2",
    crescentExpired: "dddddddd-dddd-dddd-dddd-ddddddddddd3",
    crescentHistorical: "dddddddd-dddd-dddd-dddd-ddddddddddd4",
    crescentReusedActive: "dddddddd-dddd-dddd-dddd-ddddddddddd5",
    threeRiversSoftDeleted: "dddddddd-dddd-dddd-dddd-ddddddddddd6",
    tokyoActive: "dddddddd-dddd-dddd-dddd-ddddddddddd7",
    tokyoExpiringSoon: "dddddddd-dddd-dddd-dddd-ddddddddddd8",
    riverHalalExpired: "dddddddd-dddd-dddd-dddd-ddddddddddd9",
    eastEndHistorical: "dddddddd-dddd-dddd-dddd-dddddddddd10",
    eastEndReusedActive: "dddddddd-dddd-dddd-dddd-dddddddddd11",
    riverHalalSoftDeleted: "dddddddd-dddd-dddd-dddd-dddddddddd12",
    ryanWeekendGallon: "dddddddd-dddd-dddd-dddd-dddddddddd13",
    ryanCider2for1: "dddddddd-dddd-dddd-dddd-dddddddddd14",
  },
  alerts: {
    ninaStoreFollowLotus: "eeeeeeee-eeee-eeee-eeee-eeeeeeeeeee1",
    ninaItemRestockLamb: "eeeeeeee-eeee-eeee-eeee-eeeeeeeeeee2",
    jordanStoreFollowTokyo: "eeeeeeee-eeee-eeee-eeee-eeeeeeeeeee3",
    jordanItemRestockKale: "eeeeeeee-eeee-eeee-eeee-eeeeeeeeeee4",
  },
} as const;

export const owners = [
  {
    id: ids.owners.linh,
    email: "linh@lotus-market.test",
    name: "Linh Tran",
    passwordHash: bcrypt.hashSync(fixtureMeta.ownerPlaintextPassword, BCRYPT_SALT),
    createdAt: atDays(-45),
  },
  {
    id: ids.owners.abdullah,
    email: "abdullah@crescent-halal.test",
    name: "Abdullah Khan",
    passwordHash: bcrypt.hashSync(fixtureMeta.ownerPlaintextPassword, BCRYPT_SALT),
    createdAt: atDays(-30),
  },
  {
    id: ids.owners.maria,
    email: "maria@3rivers-produce.test",
    name: "Maria Santos",
    passwordHash: bcrypt.hashSync(fixtureMeta.ownerPlaintextPassword, BCRYPT_SALT),
    createdAt: atDays(-25),
  },
  {
    id: ids.owners.noStoreOwner,
    email: "newowner@no-store.test",
    name: "Casey Newowner",
    passwordHash: bcrypt.hashSync(fixtureMeta.ownerPlaintextPassword, BCRYPT_SALT),
    createdAt: atDays(-3),
  },
  {
    id: ids.owners.jiyeon,
    email: "jiyeon@tokyo-mart.test",
    name: "Jiyeon Park",
    passwordHash: bcrypt.hashSync(fixtureMeta.ownerPlaintextPassword, BCRYPT_SALT),
    createdAt: atDays(-22),
  },
  {
    id: ids.owners.omar,
    email: "omar@river-halal.test",
    name: "Omar Hassan",
    passwordHash: bcrypt.hashSync(fixtureMeta.ownerPlaintextPassword, BCRYPT_SALT),
    createdAt: atDays(-18),
  },
  {
    id: ids.owners.evelyn,
    email: "evelyn@eastend-organic.test",
    name: "Evelyn Brooks",
    passwordHash: bcrypt.hashSync(fixtureMeta.ownerPlaintextPassword, BCRYPT_SALT),
    createdAt: atDays(-16),
  },
  {
    id: ids.owners.noStoreOwnerTwo,
    email: "backupowner@no-store.test",
    name: "Robin Draft",
    passwordHash: bcrypt.hashSync(fixtureMeta.ownerPlaintextPassword, BCRYPT_SALT),
    createdAt: atDays(-2),
  },
  {
    id: ids.owners.ryanAppleJuice,
    email: "ryanw3@andrew.cmu.edu",
    name: "Ryan",
    passwordHash: bcrypt.hashSync(fixtureMeta.ownerPlaintextPassword, BCRYPT_SALT),
    createdAt: atDays(-14),
  },
];

export const stores = [
  {
    id: ids.stores.lotus,
    ownerId: ids.owners.linh,
    name: "Lotus Asian Market",
    address: "5899 Forbes Ave, Pittsburgh, PA 15217",
    lat: 40.43734,
    lng: -79.92148,
    categories: ["asian", "produce"],
    isPublished: true,
    createdAt: atDays(-40),
  },
  {
    id: ids.stores.crescent,
    ownerId: ids.owners.abdullah,
    name: "Crescent Halal Grocer",
    address: "202 Brownsville Rd, Pittsburgh, PA 15210",
    lat: 40.40502,
    lng: -79.98631,
    categories: ["halal", "ebt"],
    isPublished: true,
    createdAt: atDays(-28),
  },
  {
    id: ids.stores.threeRivers,
    ownerId: ids.owners.maria,
    name: "Three Rivers Organic Produce",
    address: "2401 Smallman St, Pittsburgh, PA 15222",
    lat: 40.45258,
    lng: -79.97938,
    categories: ["organic", "produce", "ebt"],
    isPublished: true,
    createdAt: atDays(-20),
  },
  {
    id: ids.stores.tokyoMart,
    ownerId: ids.owners.jiyeon,
    name: "Tokyo Mart Shadyside",
    address: "5525 Walnut St, Pittsburgh, PA 15232",
    lat: 40.45131,
    lng: -79.9345,
    categories: ["asian", "ebt"],
    isPublished: true,
    createdAt: atDays(-18),
  },
  {
    id: ids.stores.riverHalalHub,
    ownerId: ids.owners.omar,
    name: "River Halal Hub",
    address: "3115 Banksville Rd, Pittsburgh, PA 15216",
    lat: 40.41403,
    lng: -80.03962,
    categories: ["halal", "produce"],
    isPublished: true,
    createdAt: atDays(-15),
  },
  {
    id: ids.stores.eastEndOrganic,
    ownerId: ids.owners.evelyn,
    name: "East End Organic Pantry",
    address: "6400 Penn Ave, Pittsburgh, PA 15206",
    lat: 40.4609,
    lng: -79.91922,
    categories: ["organic", "produce", "ebt"],
    isPublished: true,
    createdAt: atDays(-12),
  },
  {
    id: ids.stores.ryanAppleJuice,
    ownerId: ids.owners.ryanAppleJuice,
    name: "Ryan's Apple Juice",
    address: "5883 Wilkins Ave, Pittsburgh, PA 15217",
    lat: 40.4372,
    lng: -79.9148,
    categories: ["organic", "produce"],
    isPublished: true,
    createdAt: atDays(-12),
    hours: { open: "08:00", close: "20:00" },
  },
];

const shopperPasswordHash = bcrypt.hashSync(
  fixtureMeta.shopperPlaintextPassword,
  BCRYPT_SALT,
);

export const shoppers = [
  {
    id: ids.shoppers.nina,
    email: "nina.shopper@testmail.com",
    name: "Nina Shopper",
    passwordHash: shopperPasswordHash,
    createdAt: atDays(-10),
  },
  {
    id: ids.shoppers.jordan,
    email: "jordan.shopper@testmail.com",
    name: "Jordan Shopper",
    passwordHash: shopperPasswordHash,
    createdAt: atDays(-8),
  },
  {
    id: ids.shoppers.shopper03,
    email: "alex.shopper@testmail.com",
    name: "Alex Shopper",
    passwordHash: shopperPasswordHash,
    createdAt: atDays(-7),
  },
  {
    id: ids.shoppers.shopper04,
    email: "taylor.shopper@testmail.com",
    name: "Taylor Shopper",
    passwordHash: shopperPasswordHash,
    createdAt: atDays(-6),
  },
  {
    id: ids.shoppers.shopper05,
    email: "sam.shopper@testmail.com",
    name: "Sam Shopper",
    passwordHash: shopperPasswordHash,
    createdAt: atDays(-6),
  },
  {
    id: ids.shoppers.shopper06,
    email: "riley.shopper@testmail.com",
    name: "Riley Shopper",
    passwordHash: shopperPasswordHash,
    createdAt: atDays(-5),
  },
  {
    id: ids.shoppers.shopper07,
    email: "morgan.shopper@testmail.com",
    name: "Morgan Shopper",
    passwordHash: shopperPasswordHash,
    createdAt: atDays(-5),
  },
  {
    id: ids.shoppers.shopper08,
    email: "jamie.shopper@testmail.com",
    name: "Jamie Shopper",
    passwordHash: shopperPasswordHash,
    createdAt: atDays(-4),
  },
  {
    id: ids.shoppers.shopper09,
    email: "drew.shopper@testmail.com",
    name: "Drew Shopper",
    passwordHash: shopperPasswordHash,
    createdAt: atDays(-4),
  },
  {
    id: ids.shoppers.shopper10,
    email: "casey.shopper2@testmail.com",
    name: "Casey Shopper",
    passwordHash: shopperPasswordHash,
    createdAt: atDays(-3),
  },
  {
    id: ids.shoppers.shopper11,
    email: "cameron.shopper@testmail.com",
    name: "Cameron Shopper",
    passwordHash: shopperPasswordHash,
    createdAt: atDays(-3),
  },
  {
    id: ids.shoppers.shopper12,
    email: "peyton.shopper@testmail.com",
    name: "Peyton Shopper",
    passwordHash: shopperPasswordHash,
    createdAt: atDays(-2),
  },
];

export const items = [
  {
    id: ids.items.bokChoy,
    storeId: ids.stores.lotus,
    name: "Baby Bok Choy",
    description: "Crisp bunches from regional growers",
    inStock: true,
    lastUpdated: atHours(-3),
  },
  {
    id: ids.items.bokChoiTypo,
    storeId: ids.stores.lotus,
    name: "Bok Choi Family Pack",
    description: "Intentional spelling variant for fuzzy search QA",
    inStock: false,
    lastUpdated: atDays(-2),
  },
  {
    id: ids.items.ramen,
    storeId: ids.stores.lotus,
    name: "Shin Ramyun 4-Pack",
    description: "Spicy instant noodle multipack",
    inStock: true,
    lastUpdated: atHours(-6),
  },
  {
    id: ids.items.halalLambShoulder,
    storeId: ids.stores.crescent,
    name: "Halal Lamb Shoulder",
    description: "Fresh halal-certified lamb shoulder cuts",
    inStock: true,
    lastUpdated: atHours(-2),
  },
  {
    id: ids.items.cilantro,
    storeId: ids.stores.crescent,
    name: "Cillantro Bunch",
    description: "Intentional typo to test search tolerance",
    inStock: true,
    lastUpdated: atHours(-5),
  },
  {
    id: ids.items.spinach,
    storeId: ids.stores.threeRivers,
    name: "Organic Spinach",
    description: "Organic bunch spinach",
    inStock: false,
    lastUpdated: atDays(-4),
  },
  {
    id: ids.items.oatMilk,
    storeId: ids.stores.threeRivers,
    name: "Oat Milk Unsweetened",
    description: "Dairy-free staple",
    inStock: true,
    lastUpdated: atHours(-7),
  },
  {
    id: ids.items.napaCabbage,
    storeId: ids.stores.tokyoMart,
    name: "Napa Cabbage",
    description: "Fresh napa cabbage heads",
    inStock: true,
    lastUpdated: atHours(-4),
  },
  {
    id: ids.items.gochujang,
    storeId: ids.stores.tokyoMart,
    name: "Gochujang Paste",
    description: "Korean chili paste",
    inStock: true,
    lastUpdated: atHours(-9),
  },
  {
    id: ids.items.halalChickenThighs,
    storeId: ids.stores.riverHalalHub,
    name: "Halal Chicken Thighs",
    description: "Fresh halal chicken cuts",
    inStock: false,
    lastUpdated: atDays(-1),
  },
  {
    id: ids.items.datesMedjool,
    storeId: ids.stores.riverHalalHub,
    name: "Medjool Dates",
    description: "Imported premium dates",
    inStock: true,
    lastUpdated: atHours(-11),
  },
  {
    id: ids.items.kale,
    storeId: ids.stores.eastEndOrganic,
    name: "Organic Kale",
    description: "Locally grown kale bunches",
    inStock: true,
    lastUpdated: atHours(-13),
  },
  {
    id: ids.items.sourdough,
    storeId: ids.stores.eastEndOrganic,
    name: "Whole Grain Sourdough",
    description: "Fresh bakery loaf",
    inStock: true,
    lastUpdated: atHours(-15),
  },
  {
    id: ids.items.tomatoeSauceTypo,
    storeId: ids.stores.eastEndOrganic,
    name: "Tomatoe Sauce",
    description: "Intentional typo for fuzzy search testing",
    inStock: false,
    lastUpdated: atDays(-3),
  },
  {
    id: ids.items.ryanJuice64oz,
    storeId: ids.stores.ryanAppleJuice,
    name: "Fresh Pressed Apple Juice 64oz",
    description: "Cold-pressed local apples, no added sugar",
    inStock: true,
    lastUpdated: atHours(-5),
  },
  {
    id: ids.items.ryanHoneycrispCider,
    storeId: ids.stores.ryanAppleJuice,
    name: "Honeycrisp Apple Cider",
    description: "Small-batch seasonal cider",
    inStock: true,
    lastUpdated: atHours(-8),
  },
];

export const freshUpdates = [
  {
    id: ids.freshUpdates.lotusRecent,
    storeId: ids.stores.lotus,
    itemId: ids.items.bokChoy,
    itemName: "Baby Bok Choy",
    note: "Fresh delivery arrived this morning.",
    createdAt: atHours(-8),
    deletedAt: null,
  },
  {
    id: ids.freshUpdates.crescentRecent,
    storeId: ids.stores.crescent,
    itemId: ids.items.halalLambShoulder,
    itemName: "Halal Lamb Shoulder",
    note: "Halal certified cuts available today.",
    createdAt: atHours(-20),
    deletedAt: null,
  },
  {
    id: ids.freshUpdates.threeRiversStale,
    storeId: ids.stores.threeRivers,
    itemId: ids.items.spinach,
    itemName: "Organic Spinach",
    note: "Posted earlier this week; should now be stale.",
    createdAt: atDays(-4),
    deletedAt: null,
  },
  {
    id: ids.freshUpdates.lotusSoftDeleted,
    storeId: ids.stores.lotus,
    itemId: ids.items.bokChoiTypo,
    itemName: "Bok Choi Family Pack",
    note: "Removed by owner after stock ran out.",
    createdAt: atHours(-22),
    deletedAt: atHours(-2),
  },
  {
    id: ids.freshUpdates.tokyoRecent,
    storeId: ids.stores.tokyoMart,
    itemId: ids.items.napaCabbage,
    itemName: "Napa Cabbage",
    note: "Fresh heads arrived from this morning shipment.",
    createdAt: atHours(-6),
    deletedAt: null,
  },
  {
    id: ids.freshUpdates.riverHalalRecent,
    storeId: ids.stores.riverHalalHub,
    itemId: ids.items.datesMedjool,
    itemName: "Medjool Dates",
    note: "New batch stocked at opening.",
    createdAt: atHours(-14),
    deletedAt: null,
  },
  {
    id: ids.freshUpdates.eastEndStale,
    storeId: ids.stores.eastEndOrganic,
    itemId: ids.items.tomatoeSauceTypo,
    itemName: "Tomatoe Sauce",
    note: "Older post to test stale filtering behavior.",
    createdAt: atDays(-5),
    deletedAt: null,
  },
  {
    id: ids.freshUpdates.tokyoSoftDeleted,
    storeId: ids.stores.tokyoMart,
    itemId: ids.items.gochujang,
    itemName: "Gochujang Paste",
    note: "Deleted after owner corrected inventory status.",
    createdAt: atHours(-25),
    deletedAt: atHours(-4),
  },
  {
    id: ids.freshUpdates.ryanRecentJuice,
    storeId: ids.stores.ryanAppleJuice,
    itemId: ids.items.ryanJuice64oz,
    itemName: "Fresh Pressed Apple Juice 64oz",
    note: "New pressing — crisp and sweet today.",
    createdAt: atHours(-6),
    deletedAt: null,
  },
  {
    id: ids.freshUpdates.ryanRecentCider,
    storeId: ids.stores.ryanAppleJuice,
    itemId: ids.items.ryanHoneycrispCider,
    itemName: "Honeycrisp Apple Cider",
    note: "Back in stock for the weekend.",
    createdAt: atHours(-18),
    deletedAt: null,
  },
  {
    id: ids.freshUpdates.ryanOrganicNote,
    storeId: ids.stores.ryanAppleJuice,
    itemId: ids.items.ryanJuice64oz,
    itemName: "Fresh Pressed Apple Juice 64oz",
    note: "Organic certified apples — limited run.",
    createdAt: atHours(-42),
    deletedAt: null,
  },
];

export const deals = [
  {
    id: ids.deals.lotusActive,
    storeId: ids.stores.lotus,
    itemId: ids.items.ramen,
    sourceDealId: null,
    title: "Shin Ramyun buy 3 get 1 free",
    description: "Stock up on your favorite spicy noodles at a great price.",
    price: new Prisma.Decimal("4.99"),
    discountPct: 25,
    expiresAt: atDays(3),
    isExpired: false,
    createdAt: atHours(-30),
    deletedAt: null,
  },
  {
    id: ids.deals.lotusExpiringSoon,
    storeId: ids.stores.lotus,
    itemId: ids.items.bokChoy,
    sourceDealId: null,
    title: "20% off Baby Bok Choy",
    description: "Fresh produce at special prices — don't miss this week's deal.",
    price: new Prisma.Decimal("2.49"),
    discountPct: 20,
    expiresAt: atHours(12),
    isExpired: false,
    createdAt: atHours(-12),
    deletedAt: null,
  },
  {
    id: ids.deals.crescentExpired,
    storeId: ids.stores.crescent,
    itemId: ids.items.halalLambShoulder,
    sourceDealId: null,
    title: "30% off lamb shoulder",
    description: "Weekly special on premium halal cuts while supplies last.",
    price: new Prisma.Decimal("12.99"),
    discountPct: 30,
    expiresAt: atHours(-6),
    isExpired: true,
    createdAt: atDays(-4),
    deletedAt: null,
  },
  {
    id: ids.deals.crescentHistorical,
    storeId: ids.stores.crescent,
    itemId: ids.items.halalLambShoulder,
    sourceDealId: null,
    title: "Past lamb special (historical)",
    description: "Limited-time savings on lamb — great for weekend cooking.",
    price: new Prisma.Decimal("11.49"),
    discountPct: 15,
    expiresAt: atDays(-7),
    isExpired: true,
    createdAt: atDays(-14),
    deletedAt: null,
  },
  {
    id: ids.deals.crescentReusedActive,
    storeId: ids.stores.crescent,
    itemId: ids.items.halalLambShoulder,
    sourceDealId: ids.deals.crescentHistorical,
    title: "Past lamb special (reused this week)",
    description: "This week's halal lamb special is back — same great price.",
    price: new Prisma.Decimal("11.49"),
    discountPct: 15,
    expiresAt: atDays(2),
    isExpired: false,
    createdAt: atHours(-1),
    deletedAt: null,
  },
  {
    id: ids.deals.threeRiversSoftDeleted,
    storeId: ids.stores.threeRivers,
    itemId: ids.items.oatMilk,
    sourceDealId: null,
    title: "Soft-deleted oat milk flash sale",
    description: "Short-run flash sale on oat milk — grab yours before it's gone.",
    price: new Prisma.Decimal("3.29"),
    discountPct: 10,
    expiresAt: atDays(1),
    isExpired: false,
    createdAt: atHours(-10),
    deletedAt: atHours(-3),
  },
  {
    id: ids.deals.tokyoActive,
    storeId: ids.stores.tokyoMart,
    itemId: ids.items.gochujang,
    sourceDealId: null,
    title: "15% off Gochujang",
    description: "Add bold flavor to your kitchen — Korean chili paste on sale.",
    price: new Prisma.Decimal("5.49"),
    discountPct: 15,
    expiresAt: atDays(4),
    isExpired: false,
    createdAt: atHours(-18),
    deletedAt: null,
  },
  {
    id: ids.deals.tokyoExpiringSoon,
    storeId: ids.stores.tokyoMart,
    itemId: ids.items.napaCabbage,
    sourceDealId: null,
    title: "Napa cabbage 2-for-1",
    description: "Two for the price of one — fresh napa cabbage, today only.",
    price: new Prisma.Decimal("1.99"),
    discountPct: null,
    expiresAt: atHours(8),
    isExpired: false,
    createdAt: atHours(-7),
    deletedAt: null,
  },
  {
    id: ids.deals.riverHalalExpired,
    storeId: ids.stores.riverHalalHub,
    itemId: ids.items.halalChickenThighs,
    sourceDealId: null,
    title: "25% off halal chicken thighs",
    description: "Midweek savings on fresh halal chicken thighs.",
    price: new Prisma.Decimal("6.99"),
    discountPct: 25,
    expiresAt: atHours(-20),
    isExpired: true,
    createdAt: atDays(-3),
    deletedAt: null,
  },
  {
    id: ids.deals.eastEndHistorical,
    storeId: ids.stores.eastEndOrganic,
    itemId: ids.items.kale,
    sourceDealId: null,
    title: "Past organic greens bundle",
    description: "Mix and match organic greens for one bundle price.",
    price: new Prisma.Decimal("7.99"),
    discountPct: 18,
    expiresAt: atDays(-10),
    isExpired: true,
    createdAt: atDays(-17),
    deletedAt: null,
  },
  {
    id: ids.deals.eastEndReusedActive,
    storeId: ids.stores.eastEndOrganic,
    itemId: ids.items.kale,
    sourceDealId: ids.deals.eastEndHistorical,
    title: "Past organic greens bundle (reused)",
    description: "Organic greens bundle is back — same great value as before.",
    price: new Prisma.Decimal("7.99"),
    discountPct: 18,
    expiresAt: atDays(5),
    isExpired: false,
    createdAt: atHours(-2),
    deletedAt: null,
  },
  {
    id: ids.deals.riverHalalSoftDeleted,
    storeId: ids.stores.riverHalalHub,
    itemId: ids.items.datesMedjool,
    sourceDealId: null,
    title: "Soft-deleted dates weekend promo",
    description: "Weekend promo on premium Medjool dates — sweet savings.",
    price: new Prisma.Decimal("8.49"),
    discountPct: 12,
    expiresAt: atDays(2),
    isExpired: false,
    createdAt: atHours(-16),
    deletedAt: atHours(-6),
  },
  {
    id: ids.deals.ryanWeekendGallon,
    storeId: ids.stores.ryanAppleJuice,
    itemId: ids.items.ryanJuice64oz,
    sourceDealId: null,
    title: "$1 off gallon jugs this weekend",
    description: "64oz fresh pressed — ends Sunday night.",
    price: new Prisma.Decimal("7.99"),
    discountPct: 11,
    expiresAt: atDays(4),
    isExpired: false,
    createdAt: atHours(-20),
    deletedAt: null,
  },
  {
    id: ids.deals.ryanCider2for1,
    storeId: ids.stores.ryanAppleJuice,
    itemId: ids.items.ryanHoneycrispCider,
    sourceDealId: null,
    title: "Honeycrisp cider 2 for 1",
    description: "Mix and match with any 32oz bottle.",
    price: new Prisma.Decimal("5.49"),
    discountPct: 50,
    expiresAt: atHours(36),
    isExpired: false,
    createdAt: atHours(-8),
    deletedAt: null,
  },
];

export const alerts = [
  {
    id: ids.alerts.ninaStoreFollowLotus,
    shopperId: ids.shoppers.nina,
    storeId: ids.stores.lotus,
    itemId: null,
    type: "store_follow" as const,
    isActive: true,
    createdAt: atDays(-1),
  },
  {
    id: ids.alerts.ninaItemRestockLamb,
    shopperId: ids.shoppers.nina,
    storeId: ids.stores.crescent,
    itemId: ids.items.halalLambShoulder,
    type: "item_restock" as const,
    isActive: true,
    createdAt: atHours(-5),
  },
  {
    id: ids.alerts.jordanStoreFollowTokyo,
    shopperId: ids.shoppers.jordan,
    storeId: ids.stores.tokyoMart,
    itemId: null,
    type: "store_follow" as const,
    isActive: true,
    createdAt: atHours(-9),
  },
  {
    id: ids.alerts.jordanItemRestockKale,
    shopperId: ids.shoppers.jordan,
    storeId: ids.stores.eastEndOrganic,
    itemId: ids.items.kale,
    type: "item_restock" as const,
    isActive: true,
    createdAt: atHours(-4),
  },
];

const RYAN_SEARCH_QUERIES = [
  "apple",
  "apple juice",
  "juice",
  "cider",
  "gallon",
  "organic",
  "honeycrisp",
  "press",
];

/** Deterministic profile view events for Ryan's Apple Juice (rolling ~30 days) */
export const storeProfileViewsSeed = Array.from({ length: 38 }, (_, i) => ({
  storeId: ids.stores.ryanAppleJuice,
  createdAt: atHours(-i * 19 - 1),
}));

/** Deterministic item search events for Ryan's Apple Juice */
export const storeItemSearchesSeed = Array.from({ length: 22 }, (_, i) => ({
  storeId: ids.stores.ryanAppleJuice,
  query: RYAN_SEARCH_QUERIES[i % RYAN_SEARCH_QUERIES.length],
  createdAt: atHours(-i * 31 - 4),
}));
