import bcrypt from "bcryptjs";
import { Prisma } from "../app/generated/prisma/client";

// Set SEED_BASE_TIME=<ISO string> for deterministic CI seeding; defaults to now.
const BASE_TIME = process.env.SEED_BASE_TIME
  ? new Date(process.env.SEED_BASE_TIME)
  : new Date();
const BCRYPT_SALT = "$2b$10$CwTycUXWue0Thq9StjUM0u";

const atHours = (deltaHours: number) =>
  new Date(BASE_TIME.getTime() + deltaHours * 60 * 60 * 1000);

const atDays = (deltaDays: number) => atHours(deltaDays * 24);

export const fixtureMeta = {
  baseTime: BASE_TIME,
  publicNowHint: BASE_TIME.toISOString(),
  ownerPlaintextPassword: "OwnerPass123!",
  shopperPlaintextPassword: "ShopperPass123!",
};

export const ids = {
  owners: {
    linh: "11111111-1111-1111-1111-111111111111",
    abdullah: "22222222-2222-2222-2222-222222222222",
    maria: "33333333-3333-3333-3333-333333333333",
    noStoreOwner: "44444444-4444-4444-4444-444444444444",
    jiyeon: "66666666-6666-6666-6666-666666666661",
    omar: "66666666-6666-6666-6666-666666666662",
    evelyn: "66666666-6666-6666-6666-666666666663",
    noStoreOwnerTwo: "66666666-6666-6666-6666-666666666664",
    pressJuice: "77777777-7777-7777-7777-777777777777",
  },
  stores: {
    lotus: "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa1",
    crescent: "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa2",
    threeRivers: "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa3",
    tokyoMart: "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa4",
    riverHalalHub: "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa5",
    eastEndOrganic: "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa6",
    pressJuice: "88888888-8888-8888-8888-888888888888",
  },
  shoppers: {
    nina: "55555555-5555-5555-5555-555555555555",
    jordan: "55555555-5555-5555-5555-555555555556",
    shopper03: "55555555-5555-5555-5555-555555555557",
    shopper04: "55555555-5555-5555-5555-555555555558",
    shopper05: "55555555-5555-5555-5555-555555555559",
    shopper06: "55555555-5555-5555-5555-555555555560",
    shopper07: "55555555-5555-5555-5555-555555555561",
    shopper08: "55555555-5555-5555-5555-555555555562",
    shopper09: "55555555-5555-5555-5555-555555555563",
    shopper10: "55555555-5555-5555-5555-555555555564",
    shopper11: "55555555-5555-5555-5555-555555555565",
    shopper12: "55555555-5555-5555-5555-555555555566",
  },
  items: {
    // Lotus Asian Market (original 3)
    bokChoy: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb1",
    bokChoiTypo: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb2",
    ramen: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb6",
    // Crescent Halal Grocer (original 2)
    halalLambShoulder: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb3",
    cilantro: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb7",
    // Three Rivers Organic (original 2)
    spinach: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb4",
    oatMilk: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb5",
    // Tokyo Mart (original 2)
    napaCabbage: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb8",
    gochujang: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb9",
    // River Halal Hub (original 2)
    halalChickenThighs: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbb10",
    datesMedjool: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbb11",
    // East End Organic Pantry (original 3)
    kale: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbb12",
    sourdough: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbb13",
    tomatoeSauceTypo: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbb14",
    // The Press Juice Co. (original 2)
    pressJuice64oz: "99999999-9999-9999-9999-999999999991",
    pressHoneycrispCider: "99999999-9999-9999-9999-999999999992",

    // Lotus Asian Market — new items
    jasmineRice: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbb15",
    fishSauce: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbb16",
    galbi: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbb17",
    phoNoodles: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbb18",
    sambalOelek: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbb19",
    thaiBasil: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbb20",

    // Crescent Halal Grocer — new items
    halalGroundBeef: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbb21",
    basmatiRice: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbb22",
    driedChickpeas: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbb23",
    halalMerguez: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbb24",
    pitaBread: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbb25",
    harissa: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbb26",

    // Three Rivers Organic Produce — new items
    rainbowCarrots: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbb27",
    heirloomTomatoes: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbb28",
    organicApples: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbb29",
    babyArugula: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbb30",
    sweetPotatoes: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbb31",
    pastureEggs: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbb32",

    // Tokyo Mart Shadyside — new items
    soySauce: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbb33",
    mirin: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbb34",
    nori: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbb35",
    freshUdon: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbb36",
    sesameOil: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbb37",
    firmTofu: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbb38",
    houseKimchi: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbb39",

    // River Halal Hub — new items
    halalGoat: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbb40",
    roseWater: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbb41",
    pomMolasses: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbb42",
    halalChickenBreast: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbb43",
    sumac: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbb44",
    driedApricots: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbb45",

    // East End Organic Pantry — new items
    grassFedButter: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbb46",
    rawHoney: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbb47",
    organicBlueberries: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbb48",
    stoneGroundGrits: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbb49",
    organicGarlic: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbb50",

    // The Press Juice Co. — new items
    watermelonMintJuice: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbb51",
    carrotGingerJuice: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbb52",
    greenDetoxJuice: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbb53",
    seasonalFruitBasket: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbb54",
  },
  freshUpdates: {
    // original
    lotusRecent: "cccccccc-cccc-cccc-cccc-ccccccccccc1",
    crescentRecent: "cccccccc-cccc-cccc-cccc-ccccccccccc2",
    threeRiversStale: "cccccccc-cccc-cccc-cccc-ccccccccccc3",
    lotusSoftDeleted: "cccccccc-cccc-cccc-cccc-ccccccccccc4",
    tokyoRecent: "cccccccc-cccc-cccc-cccc-ccccccccccc5",
    riverHalalRecent: "cccccccc-cccc-cccc-cccc-ccccccccccc6",
    eastEndStale: "cccccccc-cccc-cccc-cccc-ccccccccccc7",
    tokyoSoftDeleted: "cccccccc-cccc-cccc-cccc-ccccccccccc8",
    pressRecentJuice: "cccccccc-cccc-cccc-cccc-cccccccccc01",
    pressRecentCider: "cccccccc-cccc-cccc-cccc-cccccccccc02",
    pressOrganicNote: "cccccccc-cccc-cccc-cccc-cccccccccc03",
    // new
    lotusGalbi: "cccccccc-cccc-cccc-cccc-cccccccccc04",
    lotusThaiBasil: "cccccccc-cccc-cccc-cccc-cccccccccc05",
    crescentPita: "cccccccc-cccc-cccc-cccc-cccccccccc06",
    threeRiversTomatoes: "cccccccc-cccc-cccc-cccc-cccccccccc07",
    threeRiversEggs: "cccccccc-cccc-cccc-cccc-cccccccccc08",
    eastEndHoney: "cccccccc-cccc-cccc-cccc-cccccccccc09",
    eastEndBlueberries: "cccccccc-cccc-cccc-cccc-cccccccccc10",
    pressWatermelon: "cccccccc-cccc-cccc-cccc-cccccccccc11",
    riverHalalGoat: "cccccccc-cccc-cccc-cccc-cccccccccc12",
    tokyoKimchi: "cccccccc-cccc-cccc-cccc-cccccccccc13",
    crescentHarissa: "cccccccc-cccc-cccc-cccc-cccccccccc14",
    crescentGroundBeef: "cccccccc-cccc-cccc-cccc-cccccccccc15",
    riverHalalChicken: "cccccccc-cccc-cccc-cccc-cccccccccc16",
    riverHalalApricots: "cccccccc-cccc-cccc-cccc-cccccccccc17",
  },
  deals: {
    lotusActive: "dddddddd-dddd-dddd-dddd-ddddddddddd1",
    lotusExpiringSoon: "dddddddd-dddd-dddd-dddd-ddddddddddd2",
    crescentExpired: "dddddddd-dddd-dddd-dddd-ddddddddddd3",
    crescentHistorical: "dddddddd-dddd-dddd-dddd-ddddddddddd4",
    crescentReusedActive: "dddddddd-dddd-dddd-dddd-ddddddddddd5",
    threeRiversSoftDeleted: "dddddddd-dddd-dddd-dddd-ddddddddddd6",
    tokyoActive: "dddddddd-dddd-dddd-dddd-ddddddddddd7",
    tokyoExpiringSoon: "dddddddd-dddd-dddd-dddd-ddddddddddd8",
    riverHalalExpired: "dddddddd-dddd-dddd-dddd-ddddddddddd9",
    eastEndHistorical: "dddddddd-dddd-dddd-dddd-dddddddddd10",
    eastEndReusedActive: "dddddddd-dddd-dddd-dddd-dddddddddd11",
    riverHalalSoftDeleted: "dddddddd-dddd-dddd-dddd-dddddddddd12",
    pressWeekendGallon: "dddddddd-dddd-dddd-dddd-dddddddddd13",
    pressCider2for1: "dddddddd-dddd-dddd-dddd-dddddddddd14",
    // new
    lotusRicePromo: "dddddddd-dddd-dddd-dddd-dddddddddd15",
    crescentChickpeaSale: "dddddddd-dddd-dddd-dddd-dddddddddd16",
    threeRiversEggBundle: "dddddddd-dddd-dddd-dddd-dddddddddd17",
    tokyoUdonDeal: "dddddddd-dddd-dddd-dddd-dddddddddd18",
    riverHalalGoatWeekend: "dddddddd-dddd-dddd-dddd-dddddddddd19",
    eastEndHoneyPromo: "dddddddd-dddd-dddd-dddd-dddddddddd20",
    pressGreenJuice: "dddddddd-dddd-dddd-dddd-dddddddddd21",
    threeRiversApplesPromo: "dddddddd-dddd-dddd-dddd-dddddddddd22",
    riverHalalChickenDeal: "dddddddd-dddd-dddd-dddd-dddddddddd23",
  },
  alerts: {
    ninaStoreFollowLotus: "eeeeeeee-eeee-eeee-eeee-eeeeeeeeeee1",
    ninaItemRestockLamb: "eeeeeeee-eeee-eeee-eeee-eeeeeeeeeee2",
    jordanStoreFollowTokyo: "eeeeeeee-eeee-eeee-eeee-eeeeeeeeeee3",
    jordanItemRestockKale: "eeeeeeee-eeee-eeee-eeee-eeeeeeeeeee4",
    alexFollowThreeRivers: "eeeeeeee-eeee-eeee-eeee-eeeeeeeeeee5",
    taylorFollowRiverHalal: "eeeeeeee-eeee-eeee-eeee-eeeeeeeeeee6",
    samFollowLotus: "eeeeeeee-eeee-eeee-eeee-eeeeeeeeeee7",
    morganFollowEastEnd: "eeeeeeee-eeee-eeee-eeee-eeeeeeeeeee8",
    rileyFollowTokyo: "eeeeeeee-eeee-eeee-eeee-eeeeeeeeeee9",
    cameronFollowPress: "eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeea",
    drewRestockChicken: "eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeeb",
  },
  ratings: {
    ninaLotus: "ffffffff-ffff-ffff-ffff-fffffffffff1",
    ninaCrescent: "ffffffff-ffff-ffff-ffff-fffffffffff2",
    jordanTokyo: "ffffffff-ffff-ffff-ffff-fffffffffff3",
    jordanEastEnd: "ffffffff-ffff-ffff-ffff-fffffffffff4",
    alexThreeRivers: "ffffffff-ffff-ffff-ffff-fffffffffff5",
    taylorRiverHalal: "ffffffff-ffff-ffff-ffff-fffffffffff6",
    samLotus: "ffffffff-ffff-ffff-ffff-fffffffffff7",
    morganEastEnd: "ffffffff-ffff-ffff-ffff-fffffffffff8",
    rileyLotus: "ffffffff-ffff-ffff-ffff-fffffffffff9",
    drewLotus: "ffffffff-ffff-ffff-ffff-fffffffffffa",
    samCrescent: "ffffffff-ffff-ffff-ffff-fffffffffffb",
    cameronCrescent: "ffffffff-ffff-ffff-ffff-fffffffffffc",
    rileyThreeRivers: "ffffffff-ffff-ffff-ffff-fffffffffffd",
    jordanThreeRivers: "ffffffff-ffff-ffff-ffff-fffffffffffe",
    ninaTokyoMart: "ffffffff-ffff-ffff-ffff-ffffffffffff",
    alexTokyoMart: "ffffffff-ffff-ffff-ffff-ff0000000001",
    samRiverHalal: "ffffffff-ffff-ffff-ffff-ff0000000002",
    cameronRiverHalal: "ffffffff-ffff-ffff-ffff-ff0000000003",
    drewEastEnd: "ffffffff-ffff-ffff-ffff-ff0000000004",
    ninaPressJuice: "ffffffff-ffff-ffff-ffff-ff0000000005",
    taylorPressJuice: "ffffffff-ffff-ffff-ffff-ff0000000006",
    jordanPressJuice: "ffffffff-ffff-ffff-ffff-ff0000000007",
    cameronPressJuice: "ffffffff-ffff-ffff-ffff-ff0000000008",
  },
} as const;

export const owners = [
  {
    id: ids.owners.linh,
    email: "linh.tran@example.com",
    name: "Linh Tran",
    passwordHash: bcrypt.hashSync(fixtureMeta.ownerPlaintextPassword, BCRYPT_SALT),
    createdAt: atDays(-45),
  },
  {
    id: ids.owners.abdullah,
    email: "akhan.halal@example.com",
    name: "Abdullah Khan",
    passwordHash: bcrypt.hashSync(fixtureMeta.ownerPlaintextPassword, BCRYPT_SALT),
    createdAt: atDays(-30),
  },
  {
    id: ids.owners.maria,
    email: "msantos.organic@example.com",
    name: "Maria Santos",
    passwordHash: bcrypt.hashSync(fixtureMeta.ownerPlaintextPassword, BCRYPT_SALT),
    createdAt: atDays(-25),
  },
  {
    id: ids.owners.noStoreOwner,
    email: "casey.morris@example.com",
    name: "Casey Morris",
    passwordHash: bcrypt.hashSync(fixtureMeta.ownerPlaintextPassword, BCRYPT_SALT),
    createdAt: atDays(-3),
  },
  {
    id: ids.owners.jiyeon,
    email: "jpark.pgh@example.com",
    name: "Jiyeon Park",
    passwordHash: bcrypt.hashSync(fixtureMeta.ownerPlaintextPassword, BCRYPT_SALT),
    createdAt: atDays(-22),
  },
  {
    id: ids.owners.omar,
    email: "ohassan.market@example.com",
    name: "Omar Hassan",
    passwordHash: bcrypt.hashSync(fixtureMeta.ownerPlaintextPassword, BCRYPT_SALT),
    createdAt: atDays(-18),
  },
  {
    id: ids.owners.evelyn,
    email: "evelyn.brooks@example.com",
    name: "Evelyn Brooks",
    passwordHash: bcrypt.hashSync(fixtureMeta.ownerPlaintextPassword, BCRYPT_SALT),
    createdAt: atDays(-16),
  },
  {
    id: ids.owners.noStoreOwnerTwo,
    email: "robin.kim@example.com",
    name: "Robin Kim",
    passwordHash: bcrypt.hashSync(fixtureMeta.ownerPlaintextPassword, BCRYPT_SALT),
    createdAt: atDays(-2),
  },
  {
    id: ids.owners.pressJuice,
    email: "m.webb.pgh@example.com",
    name: "Marcus Webb",
    passwordHash: bcrypt.hashSync(fixtureMeta.ownerPlaintextPassword, BCRYPT_SALT),
    createdAt: atDays(-14),
  },
];

export const stores = [
  {
    id: ids.stores.lotus,
    ownerId: ids.owners.linh,
    name: "Lotus Asian Market",
    address: "5899 Forbes Ave, Pittsburgh, PA 15217",
    lat: 40.43734,
    lng: -79.92148,
    categories: ["asian", "produce"],
    isPublished: true,
    createdAt: atDays(-40),
    hours: { open: "09:00", close: "20:00" },
  },
  {
    id: ids.stores.crescent,
    ownerId: ids.owners.abdullah,
    name: "Crescent Halal Grocer",
    address: "202 Brownsville Rd, Pittsburgh, PA 15210",
    lat: 40.40502,
    lng: -79.98631,
    categories: ["halal", "ebt"],
    isPublished: true,
    createdAt: atDays(-28),
    hours: { open: "08:00", close: "22:00" },
  },
  {
    id: ids.stores.threeRivers,
    ownerId: ids.owners.maria,
    name: "Three Rivers Organic Produce",
    address: "2401 Smallman St, Pittsburgh, PA 15222",
    lat: 40.45258,
    lng: -79.97938,
    categories: ["organic", "produce", "ebt"],
    isPublished: true,
    createdAt: atDays(-20),
    hours: { open: "07:00", close: "18:00" },
  },
  {
    id: ids.stores.tokyoMart,
    ownerId: ids.owners.jiyeon,
    name: "Tokyo Mart Shadyside",
    address: "5525 Walnut St, Pittsburgh, PA 15232",
    lat: 40.45131,
    lng: -79.9345,
    categories: ["asian", "ebt"],
    isPublished: true,
    createdAt: atDays(-18),
    hours: { open: "10:00", close: "21:00" },
  },
  {
    id: ids.stores.riverHalalHub,
    ownerId: ids.owners.omar,
    name: "River Halal Hub",
    address: "3115 Banksville Rd, Pittsburgh, PA 15216",
    lat: 40.41403,
    lng: -80.03962,
    categories: ["halal", "produce"],
    isPublished: true,
    createdAt: atDays(-15),
    hours: { open: "08:00", close: "21:00" },
  },
  {
    id: ids.stores.eastEndOrganic,
    ownerId: ids.owners.evelyn,
    name: "East End Organic Pantry",
    address: "6400 Penn Ave, Pittsburgh, PA 15206",
    lat: 40.4609,
    lng: -79.91922,
    categories: ["organic", "produce", "ebt"],
    isPublished: true,
    createdAt: atDays(-12),
    hours: { open: "09:00", close: "19:00" },
  },
  {
    id: ids.stores.pressJuice,
    ownerId: ids.owners.pressJuice,
    name: "The Press Juice Co.",
    address: "5883 Wilkins Ave, Pittsburgh, PA 15217",
    lat: 40.4372,
    lng: -79.9148,
    categories: ["organic", "produce"],
    isPublished: true,
    createdAt: atDays(-12),
    hours: { open: "08:00", close: "18:00" },
  },
];

const shopperPasswordHash = bcrypt.hashSync(
  fixtureMeta.shopperPlaintextPassword,
  BCRYPT_SALT,
);

export const shoppers = [
  {
    id: ids.shoppers.nina,
    email: "nina.patel@example.com",
    name: "Nina Patel",
    passwordHash: shopperPasswordHash,
    createdAt: atDays(-10),
  },
  {
    id: ids.shoppers.jordan,
    email: "j.chen.pgh@example.com",
    name: "Jordan Chen",
    passwordHash: shopperPasswordHash,
    createdAt: atDays(-8),
  },
  {
    id: ids.shoppers.shopper03,
    email: "alex.martinez@example.com",
    name: "Alex Martinez",
    passwordHash: shopperPasswordHash,
    createdAt: atDays(-7),
  },
  {
    id: ids.shoppers.shopper04,
    email: "t.williams@example.com",
    name: "Taylor Williams",
    passwordHash: shopperPasswordHash,
    createdAt: atDays(-6),
  },
  {
    id: ids.shoppers.shopper05,
    email: "sam.rodriguez@example.com",
    name: "Sam Rodriguez",
    passwordHash: shopperPasswordHash,
    createdAt: atDays(-6),
  },
  {
    id: ids.shoppers.shopper06,
    email: "riley.thompson@example.com",
    name: "Riley Thompson",
    passwordHash: shopperPasswordHash,
    createdAt: atDays(-5),
  },
  {
    id: ids.shoppers.shopper07,
    email: "morgan.lee@example.com",
    name: "Morgan Lee",
    passwordHash: shopperPasswordHash,
    createdAt: atDays(-5),
  },
  {
    id: ids.shoppers.shopper08,
    email: "jamiedavis@example.com",
    name: "Jamie Davis",
    passwordHash: shopperPasswordHash,
    createdAt: atDays(-4),
  },
  {
    id: ids.shoppers.shopper09,
    email: "d.anderson.pgh@example.com",
    name: "Drew Anderson",
    passwordHash: shopperPasswordHash,
    createdAt: atDays(-4),
  },
  {
    id: ids.shoppers.shopper10,
    email: "caseynguyen@example.com",
    name: "Casey Nguyen",
    passwordHash: shopperPasswordHash,
    createdAt: atDays(-3),
  },
  {
    id: ids.shoppers.shopper11,
    email: "cam.foster@example.com",
    name: "Cameron Foster",
    passwordHash: shopperPasswordHash,
    createdAt: atDays(-3),
  },
  {
    id: ids.shoppers.shopper12,
    email: "peyton.clark@example.com",
    name: "Peyton Clark",
    passwordHash: shopperPasswordHash,
    createdAt: atDays(-2),
  },
];

export const items = [
  // -----------------------------------------------------------------------
  // Lotus Asian Market
  // -----------------------------------------------------------------------
  {
    id: ids.items.bokChoy,
    storeId: ids.stores.lotus,
    name: "Baby Bok Choy",
    description: "Tender green heads from regional growers, great for stir-fries and soups",
    inStock: true,
    lastUpdated: atHours(-3),
  },
  {
    id: ids.items.bokChoiTypo,
    storeId: ids.stores.lotus,
    name: "Bok Choi Family Pack",
    description: "Large heads, ideal for kimchi or braised dishes",
    inStock: false,
    lastUpdated: atDays(-2),
  },
  {
    id: ids.items.ramen,
    storeId: ids.stores.lotus,
    name: "Shin Ramyun 4-Pack",
    description: "Spicy instant noodle multipack — a pantry staple",
    inStock: true,
    lastUpdated: atHours(-6),
  },
  {
    id: ids.items.jasmineRice,
    storeId: ids.stores.lotus,
    name: "Jasmine Rice 5lb",
    description: "Long-grain fragrant Thai jasmine rice, great for everyday cooking",
    inStock: true,
    lastUpdated: atHours(-10),
  },
  {
    id: ids.items.fishSauce,
    storeId: ids.stores.lotus,
    name: "Fish Sauce (Tiparos) 23oz",
    description: "Classic Thai fish sauce, essential for marinades, dips, and stir-fries",
    inStock: true,
    lastUpdated: atDays(-1),
  },
  {
    id: ids.items.galbi,
    storeId: ids.stores.lotus,
    name: "Galbi (Korean Short Ribs)",
    description: "Thin-cut bone-in short ribs, pre-marinated and ready to grill",
    inStock: true,
    lastUpdated: atHours(-4),
  },
  {
    id: ids.items.phoNoodles,
    storeId: ids.stores.lotus,
    name: "Pho Noodles (rice sticks) 16oz",
    description: "Dried flat rice noodles, the right width for authentic pho",
    inStock: true,
    lastUpdated: atDays(-3),
  },
  {
    id: ids.items.sambalOelek,
    storeId: ids.stores.lotus,
    name: "Sambal Oelek Chili Paste",
    description: "Fresh ground chili paste with no garlic — versatile heat for any dish",
    inStock: true,
    lastUpdated: atHours(-26),
  },
  {
    id: ids.items.thaiBasil,
    storeId: ids.stores.lotus,
    name: "Thai Basil",
    description: "Fresh bunches with a slightly anise-forward flavor, great for curries",
    inStock: true,
    lastUpdated: atHours(-5),
  },

  // -----------------------------------------------------------------------
  // Crescent Halal Grocer
  // -----------------------------------------------------------------------
  {
    id: ids.items.halalLambShoulder,
    storeId: ids.stores.crescent,
    name: "Halal Lamb Shoulder",
    description: "Fresh halal-certified lamb shoulder, cut to order on request",
    inStock: true,
    lastUpdated: atHours(-2),
  },
  {
    id: ids.items.cilantro,
    storeId: ids.stores.crescent,
    name: "Cillantro Bunch",
    description: "Fresh herb bunches, great for salsa, curries, and garnishes",
    inStock: true,
    lastUpdated: atHours(-5),
  },
  {
    id: ids.items.halalGroundBeef,
    storeId: ids.stores.crescent,
    name: "Halal Ground Beef 1lb",
    description: "80/20 lean-to-fat blend, freshly ground and halal-certified",
    inStock: true,
    lastUpdated: atHours(-3),
  },
  {
    id: ids.items.basmatiRice,
    storeId: ids.stores.crescent,
    name: "Basmati Rice 10lb",
    description: "Aged long-grain basmati, imported from Pakistan — light and fluffy",
    inStock: true,
    lastUpdated: atDays(-1),
  },
  {
    id: ids.items.driedChickpeas,
    storeId: ids.stores.crescent,
    name: "Dried Chickpeas 2lb",
    description: "Whole dried chickpeas, great for hummus, chana masala, or soups",
    inStock: true,
    lastUpdated: atDays(-2),
  },
  {
    id: ids.items.halalMerguez,
    storeId: ids.stores.crescent,
    name: "Halal Merguez Sausage",
    description: "Spiced North African lamb sausage, halal-certified — sold by the link",
    inStock: false,
    lastUpdated: atDays(-1),
  },
  {
    id: ids.items.pitaBread,
    storeId: ids.stores.crescent,
    name: "Fresh Pita Bread (6-pack)",
    description: "Baked fresh daily — soft pocket pitas, great for dipping or wraps",
    inStock: true,
    lastUpdated: atHours(-7),
  },
  {
    id: ids.items.harissa,
    storeId: ids.stores.crescent,
    name: "Harissa Paste",
    description: "Tunisian chili paste with caraway and coriander, medium heat",
    inStock: true,
    lastUpdated: atDays(-3),
  },

  // -----------------------------------------------------------------------
  // Three Rivers Organic Produce
  // -----------------------------------------------------------------------
  {
    id: ids.items.spinach,
    storeId: ids.stores.threeRivers,
    name: "Organic Spinach",
    description: "Certified organic from local farms, sold in loose bunches",
    inStock: false,
    lastUpdated: atDays(-4),
  },
  {
    id: ids.items.oatMilk,
    storeId: ids.stores.threeRivers,
    name: "Oat Milk Unsweetened",
    description: "Barista blend, unsweetened — works great in coffee",
    inStock: true,
    lastUpdated: atHours(-7),
  },
  {
    id: ids.items.rainbowCarrots,
    storeId: ids.stores.threeRivers,
    name: "Rainbow Carrots (bunch)",
    description: "Purple, orange, and yellow carrots — sweet, firm, and locally grown",
    inStock: true,
    lastUpdated: atHours(-9),
  },
  {
    id: ids.items.heirloomTomatoes,
    storeId: ids.stores.threeRivers,
    name: "Heirloom Tomatoes",
    description: "Mixed varieties from a family farm in Butler County, sold by the pound",
    inStock: true,
    lastUpdated: atHours(-4),
  },
  {
    id: ids.items.organicApples,
    storeId: ids.stores.threeRivers,
    name: "Organic Fuji Apples (3lb bag)",
    description: "Crisp and sweet, certified organic from a Pennsylvania orchard",
    inStock: true,
    lastUpdated: atHours(-11),
  },
  {
    id: ids.items.babyArugula,
    storeId: ids.stores.threeRivers,
    name: "Baby Arugula",
    description: "Peppery micro-greens, harvested young — great for salads and flatbreads",
    inStock: true,
    lastUpdated: atHours(-6),
  },
  {
    id: ids.items.sweetPotatoes,
    storeId: ids.stores.threeRivers,
    name: "Organic Sweet Potatoes",
    description: "Garnet variety, certified organic — sold loose by the pound",
    inStock: true,
    lastUpdated: atDays(-2),
  },
  {
    id: ids.items.pastureEggs,
    storeId: ids.stores.threeRivers,
    name: "Pasture-Raised Eggs (dozen)",
    description: "From a small family flock in Westmoreland County, rich orange yolks",
    inStock: true,
    lastUpdated: atHours(-8),
  },

  // -----------------------------------------------------------------------
  // Tokyo Mart Shadyside
  // -----------------------------------------------------------------------
  {
    id: ids.items.napaCabbage,
    storeId: ids.stores.tokyoMart,
    name: "Napa Cabbage",
    description: "Fresh whole heads, perfect for kimchi or hot pot",
    inStock: true,
    lastUpdated: atHours(-4),
  },
  {
    id: ids.items.gochujang,
    storeId: ids.stores.tokyoMart,
    name: "Gochujang Paste",
    description: "Traditional Korean chili paste, medium heat",
    inStock: true,
    lastUpdated: atHours(-9),
  },
  {
    id: ids.items.soySauce,
    storeId: ids.stores.tokyoMart,
    name: "Kikkoman Soy Sauce 64oz",
    description: "Naturally brewed soy sauce — the restaurant-size jug",
    inStock: true,
    lastUpdated: atDays(-1),
  },
  {
    id: ids.items.mirin,
    storeId: ids.stores.tokyoMart,
    name: "Hon Mirin (sweet rice wine) 25oz",
    description: "Authentic Japanese mirin for sauces, glazes, and marinades",
    inStock: true,
    lastUpdated: atDays(-2),
  },
  {
    id: ids.items.nori,
    storeId: ids.stores.tokyoMart,
    name: "Nori Seaweed Sheets (50-pack)",
    description: "Roasted seaweed sheets for sushi, onigiri, or snacking",
    inStock: true,
    lastUpdated: atHours(-20),
  },
  {
    id: ids.items.freshUdon,
    storeId: ids.stores.tokyoMart,
    name: "Fresh Udon Noodles",
    description: "Thick and chewy fresh-packed udon — cook in 2 minutes",
    inStock: true,
    lastUpdated: atHours(-5),
  },
  {
    id: ids.items.sesameOil,
    storeId: ids.stores.tokyoMart,
    name: "Toasted Sesame Oil 16oz",
    description: "Deep, nutty flavor — a finishing oil for noodles, stir-fries, and dressings",
    inStock: true,
    lastUpdated: atDays(-3),
  },
  {
    id: ids.items.firmTofu,
    storeId: ids.stores.tokyoMart,
    name: "Firm Tofu (2-pack)",
    description: "Water-packed firm tofu, versatile for frying, grilling, or soups",
    inStock: false,
    lastUpdated: atDays(-1),
  },
  {
    id: ids.items.houseKimchi,
    storeId: ids.stores.tokyoMart,
    name: "House-Made Kimchi 1lb jar",
    description: "Fermented in-house with napa cabbage and house seasoning — medium spice",
    inStock: true,
    lastUpdated: atHours(-10),
  },

  // -----------------------------------------------------------------------
  // River Halal Hub
  // -----------------------------------------------------------------------
  {
    id: ids.items.halalChickenThighs,
    storeId: ids.stores.riverHalalHub,
    name: "Halal Chicken Thighs",
    description: "Bone-in halal chicken thighs, fresh daily",
    inStock: false,
    lastUpdated: atDays(-1),
  },
  {
    id: ids.items.datesMedjool,
    storeId: ids.stores.riverHalalHub,
    name: "Medjool Dates",
    description: "Large premium dates imported from the Jordan Valley",
    inStock: true,
    lastUpdated: atHours(-11),
  },
  {
    id: ids.items.halalGoat,
    storeId: ids.stores.riverHalalHub,
    name: "Halal Goat Leg",
    description: "Bone-in goat leg, halal-certified — available whole or cut on request",
    inStock: true,
    lastUpdated: atHours(-6),
  },
  {
    id: ids.items.roseWater,
    storeId: ids.stores.riverHalalHub,
    name: "Rose Water 10oz",
    description: "Pure distilled rose water for desserts, drinks, and skincare",
    inStock: true,
    lastUpdated: atDays(-4),
  },
  {
    id: ids.items.pomMolasses,
    storeId: ids.stores.riverHalalHub,
    name: "Pomegranate Molasses",
    description: "Thick and tangy reduction, essential for muhammara and salad dressings",
    inStock: true,
    lastUpdated: atDays(-2),
  },
  {
    id: ids.items.halalChickenBreast,
    storeId: ids.stores.riverHalalHub,
    name: "Halal Chicken Breast",
    description: "Boneless skinless chicken breast, halal-certified — sold by the pound",
    inStock: true,
    lastUpdated: atHours(-3),
  },
  {
    id: ids.items.sumac,
    storeId: ids.stores.riverHalalHub,
    name: "Sumac (ground) 4oz",
    description: "Tangy crimson spice for fattoush, kebabs, and dips",
    inStock: true,
    lastUpdated: atDays(-5),
  },
  {
    id: ids.items.driedApricots,
    storeId: ids.stores.riverHalalHub,
    name: "Dried Apricots 1lb",
    description: "Unsulfured whole dried apricots, naturally sweet without preservatives",
    inStock: true,
    lastUpdated: atHours(-14),
  },

  // -----------------------------------------------------------------------
  // East End Organic Pantry
  // -----------------------------------------------------------------------
  {
    id: ids.items.kale,
    storeId: ids.stores.eastEndOrganic,
    name: "Organic Kale",
    description: "Locally grown curly kale, harvested within 48 hours of delivery",
    inStock: true,
    lastUpdated: atHours(-13),
  },
  {
    id: ids.items.sourdough,
    storeId: ids.stores.eastEndOrganic,
    name: "Whole Grain Sourdough",
    description: "Stone-milled whole grain loaf from a local Pittsburgh bakery",
    inStock: true,
    lastUpdated: atHours(-15),
  },
  {
    id: ids.items.tomatoeSauceTypo,
    storeId: ids.stores.eastEndOrganic,
    name: "Tomatoe Sauce",
    description: "Slow-cooked marinara with heirloom tomatoes and fresh basil",
    inStock: false,
    lastUpdated: atDays(-3),
  },
  {
    id: ids.items.grassFedButter,
    storeId: ids.stores.eastEndOrganic,
    name: "Grass-Fed Butter (salted & unsalted)",
    description: "Cultured from pasture-raised cows, rich flavor and golden color",
    inStock: true,
    lastUpdated: atHours(-16),
  },
  {
    id: ids.items.rawHoney,
    storeId: ids.stores.eastEndOrganic,
    name: "Local Raw Honey 12oz",
    description: "Unfiltered wildflower honey from a Pittsburgh-area beekeeper",
    inStock: true,
    lastUpdated: atHours(-5),
  },
  {
    id: ids.items.organicBlueberries,
    storeId: ids.stores.eastEndOrganic,
    name: "Organic Blueberries (pint)",
    description: "Certified organic, in season — sweet and plump from a local farm",
    inStock: true,
    lastUpdated: atHours(-4),
  },
  {
    id: ids.items.stoneGroundGrits,
    storeId: ids.stores.eastEndOrganic,
    name: "Stone-Ground Grits 2lb",
    description: "Coarse-ground white corn grits from a Virginia stone mill — slow-cook variety",
    inStock: true,
    lastUpdated: atDays(-5),
  },
  {
    id: ids.items.organicGarlic,
    storeId: ids.stores.eastEndOrganic,
    name: "Organic Garlic (loose)",
    description: "Locally grown organic hardneck garlic, sold by the head",
    inStock: true,
    lastUpdated: atHours(-12),
  },

  // -----------------------------------------------------------------------
  // The Press Juice Co.
  // -----------------------------------------------------------------------
  {
    id: ids.items.pressJuice64oz,
    storeId: ids.stores.pressJuice,
    name: "Fresh Pressed Apple Juice 64oz",
    description: "Cold-pressed from local Pennsylvania apples, no added sugar",
    inStock: true,
    lastUpdated: atHours(-5),
  },
  {
    id: ids.items.pressHoneycrispCider,
    storeId: ids.stores.pressJuice,
    name: "Honeycrisp Apple Cider",
    description: "Small-batch seasonal cider, slightly sweet with no preservatives",
    inStock: true,
    lastUpdated: atHours(-8),
  },
  {
    id: ids.items.watermelonMintJuice,
    storeId: ids.stores.pressJuice,
    name: "Watermelon Mint Juice 32oz",
    description: "Cold-pressed watermelon with fresh mint — refreshing and lightly sweet",
    inStock: true,
    lastUpdated: atHours(-6),
  },
  {
    id: ids.items.carrotGingerJuice,
    storeId: ids.stores.pressJuice,
    name: "Carrot Ginger Juice 32oz",
    description: "Fresh pressed with Pennsylvania carrots and raw ginger, no added sweetener",
    inStock: true,
    lastUpdated: atHours(-7),
  },
  {
    id: ids.items.greenDetoxJuice,
    storeId: ids.stores.pressJuice,
    name: "Green Detox Juice 32oz",
    description: "Kale, celery, cucumber, green apple, and lemon — cold-pressed daily",
    inStock: false,
    lastUpdated: atDays(-1),
  },
  {
    id: ids.items.seasonalFruitBasket,
    storeId: ids.stores.pressJuice,
    name: "Seasonal Fruit Basket",
    description: "Curated mix of in-season fruits from local farms — contents vary weekly",
    inStock: true,
    lastUpdated: atHours(-9),
  },
];

export const freshUpdates = [
  // -----------------------------------------------------------------------
  // Lotus Asian Market
  // -----------------------------------------------------------------------
  {
    id: ids.freshUpdates.lotusRecent,
    storeId: ids.stores.lotus,
    itemId: ids.items.bokChoy,
    itemName: "Baby Bok Choy",
    note: "Fresh delivery arrived this morning — very crisp today.",
    createdAt: atHours(-8),
    deletedAt: null,
  },
  {
    id: ids.freshUpdates.lotusSoftDeleted,
    storeId: ids.stores.lotus,
    itemId: ids.items.bokChoiTypo,
    itemName: "Bok Choi Family Pack",
    note: "Sold out faster than expected — removing this post to avoid confusion.",
    createdAt: atHours(-22),
    deletedAt: atHours(-2),
  },
  {
    id: ids.freshUpdates.lotusGalbi,
    storeId: ids.stores.lotus,
    itemId: ids.items.galbi,
    itemName: "Galbi (Korean Short Ribs)",
    note: "Fresh galbi came in from our supplier today — marinated and ready to grill.",
    createdAt: atHours(-4),
    deletedAt: null,
  },
  {
    id: ids.freshUpdates.lotusThaiBasil,
    storeId: ids.stores.lotus,
    itemId: ids.items.thaiBasil,
    itemName: "Thai Basil",
    note: "Thai basil back in stock — picked up fresh this morning.",
    createdAt: atHours(-5),
    deletedAt: null,
  },

  // -----------------------------------------------------------------------
  // Crescent Halal Grocer
  // -----------------------------------------------------------------------
  {
    id: ids.freshUpdates.crescentRecent,
    storeId: ids.stores.crescent,
    itemId: ids.items.halalLambShoulder,
    itemName: "Halal Lamb Shoulder",
    note: "Halal-certified cuts available today, freshly butchered.",
    createdAt: atHours(-20),
    deletedAt: null,
  },
  {
    id: ids.freshUpdates.crescentPita,
    storeId: ids.stores.crescent,
    itemId: ids.items.pitaBread,
    itemName: "Fresh Pita Bread (6-pack)",
    note: "Pita baked fresh this morning — soft and warm, great for wraps.",
    createdAt: atHours(-7),
    deletedAt: null,
  },
  {
    id: ids.freshUpdates.crescentHarissa,
    storeId: ids.stores.crescent,
    itemId: ids.items.harissa,
    itemName: "House Harissa",
    note: "Fresh batch of our house harissa in — mild and hot versions available.",
    createdAt: atHours(-15),
    deletedAt: null,
  },
  {
    id: ids.freshUpdates.crescentGroundBeef,
    storeId: ids.stores.crescent,
    itemId: ids.items.halalGroundBeef,
    itemName: "Halal Ground Beef",
    note: "Ground beef back after the weekend rush — freshly ground this morning, lean and extra lean available.",
    createdAt: atHours(-3),
    deletedAt: null,
  },

  // -----------------------------------------------------------------------
  // Three Rivers Organic Produce
  // -----------------------------------------------------------------------
  {
    id: ids.freshUpdates.threeRiversStale,
    storeId: ids.stores.threeRivers,
    itemId: ids.items.spinach,
    itemName: "Organic Spinach",
    note: "Restocked Tuesday from our local farm partner — call ahead if you need a large quantity.",
    createdAt: atDays(-4),
    deletedAt: null,
  },
  {
    id: ids.freshUpdates.threeRiversTomatoes,
    storeId: ids.stores.threeRivers,
    itemId: ids.items.heirloomTomatoes,
    itemName: "Heirloom Tomatoes",
    note: "Beautiful heirlooms just in from Butler County — mix of Cherokee Purple and Brandywine.",
    createdAt: atHours(-4),
    deletedAt: null,
  },
  {
    id: ids.freshUpdates.threeRiversEggs,
    storeId: ids.stores.threeRivers,
    itemId: ids.items.pastureEggs,
    itemName: "Pasture-Raised Eggs (dozen)",
    note: "Egg delivery this morning — seriously the best yolks. Go fast every week.",
    createdAt: atHours(-9),
    deletedAt: null,
  },

  // -----------------------------------------------------------------------
  // Tokyo Mart Shadyside
  // -----------------------------------------------------------------------
  {
    id: ids.freshUpdates.tokyoRecent,
    storeId: ids.stores.tokyoMart,
    itemId: ids.items.napaCabbage,
    itemName: "Napa Cabbage",
    note: "Fresh heads in from this morning's shipment — come early for best selection.",
    createdAt: atHours(-6),
    deletedAt: null,
  },
  {
    id: ids.freshUpdates.tokyoSoftDeleted,
    storeId: ids.stores.tokyoMart,
    itemId: ids.items.gochujang,
    itemName: "Gochujang Paste",
    note: "Removing this — we had more in the back than I thought. Still well stocked!",
    createdAt: atHours(-25),
    deletedAt: atHours(-4),
  },
  {
    id: ids.freshUpdates.tokyoKimchi,
    storeId: ids.stores.tokyoMart,
    itemId: ids.items.houseKimchi,
    itemName: "House-Made Kimchi 1lb jar",
    note: "New batch ready — this week's kimchi is extra tangy, fermented a full five days.",
    createdAt: atHours(-10),
    deletedAt: null,
  },

  // -----------------------------------------------------------------------
  // River Halal Hub
  // -----------------------------------------------------------------------
  {
    id: ids.freshUpdates.riverHalalRecent,
    storeId: ids.stores.riverHalalHub,
    itemId: ids.items.datesMedjool,
    itemName: "Medjool Dates",
    note: "New batch arrived at opening — perfectly ripe.",
    createdAt: atHours(-14),
    deletedAt: null,
  },
  {
    id: ids.freshUpdates.riverHalalGoat,
    storeId: ids.stores.riverHalalHub,
    itemId: ids.items.halalGoat,
    itemName: "Halal Goat Leg",
    note: "Goat leg in today — whole or cut to order. Halal-certified, very fresh.",
    createdAt: atHours(-6),
    deletedAt: null,
  },
  {
    id: ids.freshUpdates.riverHalalChicken,
    storeId: ids.stores.riverHalalHub,
    itemId: ids.items.halalChickenBreast,
    itemName: "Halal Chicken Breast",
    note: "Boneless halal chicken breast restocked this morning — skinless, great for grilling or stews.",
    createdAt: atHours(-12),
    deletedAt: null,
  },
  {
    id: ids.freshUpdates.riverHalalApricots,
    storeId: ids.stores.riverHalalHub,
    itemId: ids.items.driedApricots,
    itemName: "Sun-Dried Apricots",
    note: "New stock of unsulfured sun-dried apricots just came in — great for snacking, tagines, and baking.",
    createdAt: atHours(-7),
    deletedAt: null,
  },

  // -----------------------------------------------------------------------
  // East End Organic Pantry
  // -----------------------------------------------------------------------
  {
    id: ids.freshUpdates.eastEndStale,
    storeId: ids.stores.eastEndOrganic,
    itemId: ids.items.tomatoeSauceTypo,
    itemName: "Tomatoe Sauce",
    note: "Small batch came in earlier this week — a few jars still available.",
    createdAt: atDays(-5),
    deletedAt: null,
  },
  {
    id: ids.freshUpdates.eastEndHoney,
    storeId: ids.stores.eastEndOrganic,
    itemId: ids.items.rawHoney,
    itemName: "Local Raw Honey 12oz",
    note: "New honey in from our beekeeper in Allegheny County — light and floral.",
    createdAt: atHours(-5),
    deletedAt: null,
  },
  {
    id: ids.freshUpdates.eastEndBlueberries,
    storeId: ids.stores.eastEndOrganic,
    itemId: ids.items.organicBlueberries,
    itemName: "Organic Blueberries (pint)",
    note: "Blueberries are in season! Got a great batch today — try to come in before the weekend.",
    createdAt: atHours(-4),
    deletedAt: null,
  },

  // -----------------------------------------------------------------------
  // The Press Juice Co.
  // -----------------------------------------------------------------------
  {
    id: ids.freshUpdates.pressRecentJuice,
    storeId: ids.stores.pressJuice,
    itemId: ids.items.pressJuice64oz,
    itemName: "Fresh Pressed Apple Juice 64oz",
    note: "New pressing today — crisp and sweet, picked up this morning.",
    createdAt: atHours(-6),
    deletedAt: null,
  },
  {
    id: ids.freshUpdates.pressRecentCider,
    storeId: ids.stores.pressJuice,
    itemId: ids.items.pressHoneycrispCider,
    itemName: "Honeycrisp Apple Cider",
    note: "Back in stock for the weekend — limited bottles.",
    createdAt: atHours(-18),
    deletedAt: null,
  },
  {
    id: ids.freshUpdates.pressOrganicNote,
    storeId: ids.stores.pressJuice,
    itemId: ids.items.pressJuice64oz,
    itemName: "Fresh Pressed Apple Juice 64oz",
    note: "This week's run uses certified organic apples — limited quantity.",
    createdAt: atHours(-42),
    deletedAt: null,
  },
  {
    id: ids.freshUpdates.pressWatermelon,
    storeId: ids.stores.pressJuice,
    itemId: ids.items.watermelonMintJuice,
    itemName: "Watermelon Mint Juice 32oz",
    note: "Watermelon mint is back for the season — pressed this morning, very refreshing.",
    createdAt: atHours(-6),
    deletedAt: null,
  },
];

export const deals = [
  // -----------------------------------------------------------------------
  // Lotus Asian Market
  // -----------------------------------------------------------------------
  {
    id: ids.deals.lotusActive,
    storeId: ids.stores.lotus,
    itemId: ids.items.ramen,
    sourceDealId: null,
    title: "Shin Ramyun buy 3 get 1 free",
    description: "Stock up on your favorite spicy noodles — great value for pantry staples.",
    price: new Prisma.Decimal("4.99"),
    discountPct: 25,
    expiresAt: atDays(3),
    isExpired: false,
    createdAt: atHours(-30),
    deletedAt: null,
  },
  {
    id: ids.deals.lotusExpiringSoon,
    storeId: ids.stores.lotus,
    itemId: ids.items.bokChoy,
    sourceDealId: null,
    title: "20% off Baby Bok Choy",
    description: "Fresh-cut bundles going fast — price drop ends tonight.",
    price: new Prisma.Decimal("2.49"),
    discountPct: 20,
    expiresAt: atHours(12),
    isExpired: false,
    createdAt: atHours(-12),
    deletedAt: null,
  },
  {
    id: ids.deals.lotusRicePromo,
    storeId: ids.stores.lotus,
    itemId: ids.items.jasmineRice,
    sourceDealId: null,
    title: "Jasmine rice 2 bags for $8",
    description: "Stock your pantry — mix and match the 5lb and 10lb bags.",
    price: new Prisma.Decimal("4.49"),
    discountPct: 10,
    expiresAt: atDays(5),
    isExpired: false,
    createdAt: atHours(-15),
    deletedAt: null,
  },

  // -----------------------------------------------------------------------
  // Crescent Halal Grocer
  // -----------------------------------------------------------------------
  {
    id: ids.deals.crescentExpired,
    storeId: ids.stores.crescent,
    itemId: ids.items.halalLambShoulder,
    sourceDealId: null,
    title: "30% off lamb shoulder",
    description: "Weekend halal special on fresh lamb shoulder cuts.",
    price: new Prisma.Decimal("12.99"),
    discountPct: 30,
    expiresAt: atHours(-6),
    isExpired: true,
    createdAt: atDays(-4),
    deletedAt: null,
  },
  {
    id: ids.deals.crescentHistorical,
    storeId: ids.stores.crescent,
    itemId: ids.items.halalLambShoulder,
    sourceDealId: null,
    title: "Lamb shoulder monthly special",
    description: "Last month's regular halal butcher promotion.",
    price: new Prisma.Decimal("11.49"),
    discountPct: 15,
    expiresAt: atDays(-7),
    isExpired: true,
    createdAt: atDays(-14),
    deletedAt: null,
  },
  {
    id: ids.deals.crescentReusedActive,
    storeId: ids.stores.crescent,
    itemId: ids.items.halalLambShoulder,
    sourceDealId: ids.deals.crescentHistorical,
    title: "Lamb shoulder special — back this week",
    description: "Back by popular request — same great price as last month.",
    price: new Prisma.Decimal("11.49"),
    discountPct: 15,
    expiresAt: atDays(2),
    isExpired: false,
    createdAt: atHours(-1),
    deletedAt: null,
  },
  {
    id: ids.deals.crescentChickpeaSale,
    storeId: ids.stores.crescent,
    itemId: ids.items.driedChickpeas,
    sourceDealId: null,
    title: "Dried chickpeas — 3 bags for $7",
    description: "Great for hummus, stews, or chana masala — buy in bulk and save.",
    price: new Prisma.Decimal("2.49"),
    discountPct: 12,
    expiresAt: atDays(6),
    isExpired: false,
    createdAt: atHours(-24),
    deletedAt: null,
  },

  // -----------------------------------------------------------------------
  // Three Rivers Organic Produce
  // -----------------------------------------------------------------------
  {
    id: ids.deals.threeRiversSoftDeleted,
    storeId: ids.stores.threeRivers,
    itemId: ids.items.oatMilk,
    sourceDealId: null,
    title: "Oat milk flash sale",
    description: "Weekend sale on our most popular dairy-free staple.",
    price: new Prisma.Decimal("3.29"),
    discountPct: 10,
    expiresAt: atDays(1),
    isExpired: false,
    createdAt: atHours(-10),
    deletedAt: atHours(-3),
  },
  {
    id: ids.deals.threeRiversEggBundle,
    storeId: ids.stores.threeRivers,
    itemId: ids.items.pastureEggs,
    sourceDealId: null,
    title: "Pasture eggs — 2 dozen for $11",
    description: "Fresh from a local flock — grab two dozen while they last.",
    price: new Prisma.Decimal("5.99"),
    discountPct: 8,
    expiresAt: atDays(2),
    isExpired: false,
    createdAt: atHours(-9),
    deletedAt: null,
  },
  {
    id: ids.deals.threeRiversApplesPromo,
    storeId: ids.stores.threeRivers,
    itemId: ids.items.organicApples,
    sourceDealId: null,
    title: "Organic apples — 3lb bag for $4",
    description: "Local apples from our farm partner — mix of varieties. Great for snacking or pressing. Ends Sunday.",
    price: new Prisma.Decimal("4.00"),
    discountPct: 11,
    expiresAt: atDays(4),
    isExpired: false,
    createdAt: atHours(-6),
    deletedAt: null,
  },

  // -----------------------------------------------------------------------
  // Tokyo Mart Shadyside
  // -----------------------------------------------------------------------
  {
    id: ids.deals.tokyoActive,
    storeId: ids.stores.tokyoMart,
    itemId: ids.items.gochujang,
    sourceDealId: null,
    title: "15% off Gochujang",
    description: "Stock up your pantry — sale price this week only.",
    price: new Prisma.Decimal("5.49"),
    discountPct: 15,
    expiresAt: atDays(4),
    isExpired: false,
    createdAt: atHours(-18),
    deletedAt: null,
  },
  {
    id: ids.deals.tokyoExpiringSoon,
    storeId: ids.stores.tokyoMart,
    itemId: ids.items.napaCabbage,
    sourceDealId: null,
    title: "Napa cabbage 2-for-1",
    description: "Buy two heads, pay for one — tonight only.",
    price: new Prisma.Decimal("1.99"),
    discountPct: null,
    expiresAt: atHours(8),
    isExpired: false,
    createdAt: atHours(-7),
    deletedAt: null,
  },
  {
    id: ids.deals.tokyoUdonDeal,
    storeId: ids.stores.tokyoMart,
    itemId: ids.items.freshUdon,
    sourceDealId: null,
    title: "Fresh udon 3-pack for $5",
    description: "Perfect for a quick weeknight meal — grab a few packs.",
    price: new Prisma.Decimal("1.79"),
    discountPct: 14,
    expiresAt: atDays(3),
    isExpired: false,
    createdAt: atHours(-12),
    deletedAt: null,
  },

  // -----------------------------------------------------------------------
  // River Halal Hub
  // -----------------------------------------------------------------------
  {
    id: ids.deals.riverHalalExpired,
    storeId: ids.stores.riverHalalHub,
    itemId: ids.items.halalChickenThighs,
    sourceDealId: null,
    title: "25% off halal chicken thighs",
    description: "Eid Mubarak special — fresh halal cuts at a community discount.",
    price: new Prisma.Decimal("6.99"),
    discountPct: 25,
    expiresAt: atHours(-20),
    isExpired: true,
    createdAt: atDays(-3),
    deletedAt: null,
  },
  {
    id: ids.deals.riverHalalSoftDeleted,
    storeId: ids.stores.riverHalalHub,
    itemId: ids.items.datesMedjool,
    sourceDealId: null,
    title: "Medjool dates Ramadan special",
    description: "Special pricing on premium imported dates through the weekend.",
    price: new Prisma.Decimal("8.49"),
    discountPct: 12,
    expiresAt: atDays(2),
    isExpired: false,
    createdAt: atHours(-16),
    deletedAt: atHours(-6),
  },
  {
    id: ids.deals.riverHalalGoatWeekend,
    storeId: ids.stores.riverHalalHub,
    itemId: ids.items.halalGoat,
    sourceDealId: null,
    title: "Goat leg — $2 off per pound this weekend",
    description: "Fresh halal goat, great for slow-cook stews. Weekend special only.",
    price: new Prisma.Decimal("8.99"),
    discountPct: 18,
    expiresAt: atDays(2),
    isExpired: false,
    createdAt: atHours(-6),
    deletedAt: null,
  },
  {
    id: ids.deals.riverHalalChickenDeal,
    storeId: ids.stores.riverHalalHub,
    itemId: ids.items.halalChickenBreast,
    sourceDealId: null,
    title: "Halal chicken breast — 10% off this week",
    description: "Boneless halal chicken breast at a weekly discount. Great for grilling, stews, or stocking the freezer.",
    price: new Prisma.Decimal("7.49"),
    discountPct: 10,
    expiresAt: atDays(5),
    isExpired: false,
    createdAt: atHours(-10),
    deletedAt: null,
  },

  // -----------------------------------------------------------------------
  // East End Organic Pantry
  // -----------------------------------------------------------------------
  {
    id: ids.deals.eastEndHistorical,
    storeId: ids.stores.eastEndOrganic,
    itemId: ids.items.kale,
    sourceDealId: null,
    title: "Organic greens bundle",
    description: "Mixed kale and spinach bundles at spring season pricing.",
    price: new Prisma.Decimal("7.99"),
    discountPct: 18,
    expiresAt: atDays(-10),
    isExpired: true,
    createdAt: atDays(-17),
    deletedAt: null,
  },
  {
    id: ids.deals.eastEndReusedActive,
    storeId: ids.stores.eastEndOrganic,
    itemId: ids.items.kale,
    sourceDealId: ids.deals.eastEndHistorical,
    title: "Organic greens bundle — spring restock",
    description: "Back for the season — same bundle at the same popular price.",
    price: new Prisma.Decimal("7.99"),
    discountPct: 18,
    expiresAt: atDays(5),
    isExpired: false,
    createdAt: atHours(-2),
    deletedAt: null,
  },
  {
    id: ids.deals.eastEndHoneyPromo,
    storeId: ids.stores.eastEndOrganic,
    itemId: ids.items.rawHoney,
    sourceDealId: null,
    title: "Local honey — buy 2 get 10% off",
    description: "Stock up on raw wildflower honey before this batch runs out.",
    price: new Prisma.Decimal("9.99"),
    discountPct: 10,
    expiresAt: atDays(7),
    isExpired: false,
    createdAt: atHours(-5),
    deletedAt: null,
  },

  // -----------------------------------------------------------------------
  // The Press Juice Co.
  // -----------------------------------------------------------------------
  {
    id: ids.deals.pressWeekendGallon,
    storeId: ids.stores.pressJuice,
    itemId: ids.items.pressJuice64oz,
    sourceDealId: null,
    title: "$1 off 64oz jugs this weekend",
    description: "Fresh pressed and bottled this morning — ends Sunday night.",
    price: new Prisma.Decimal("7.99"),
    discountPct: 11,
    expiresAt: atDays(4),
    isExpired: false,
    createdAt: atHours(-20),
    deletedAt: null,
  },
  {
    id: ids.deals.pressCider2for1,
    storeId: ids.stores.pressJuice,
    itemId: ids.items.pressHoneycrispCider,
    sourceDealId: null,
    title: "Honeycrisp cider 2 for 1",
    description: "Mix and match with any 32oz bottle while supplies last.",
    price: new Prisma.Decimal("5.49"),
    discountPct: 50,
    expiresAt: atHours(36),
    isExpired: false,
    createdAt: atHours(-8),
    deletedAt: null,
  },
  {
    id: ids.deals.pressGreenJuice,
    storeId: ids.stores.pressJuice,
    itemId: ids.items.greenDetoxJuice,
    sourceDealId: null,
    title: "Green Detox Juice — intro price $6",
    description: "Try our new green blend at a special intro price this week.",
    price: new Prisma.Decimal("6.00"),
    discountPct: 14,
    expiresAt: atDays(5),
    isExpired: false,
    createdAt: atHours(-10),
    deletedAt: null,
  },
];

export const alerts = [
  {
    id: ids.alerts.ninaStoreFollowLotus,
    shopperId: ids.shoppers.nina,
    storeId: ids.stores.lotus,
    itemId: null,
    type: "store_follow" as const,
    isActive: true,
    createdAt: atDays(-1),
  },
  {
    id: ids.alerts.ninaItemRestockLamb,
    shopperId: ids.shoppers.nina,
    storeId: ids.stores.crescent,
    itemId: ids.items.halalLambShoulder,
    type: "item_restock" as const,
    isActive: true,
    createdAt: atHours(-5),
  },
  {
    id: ids.alerts.jordanStoreFollowTokyo,
    shopperId: ids.shoppers.jordan,
    storeId: ids.stores.tokyoMart,
    itemId: null,
    type: "store_follow" as const,
    isActive: true,
    createdAt: atHours(-9),
  },
  {
    id: ids.alerts.jordanItemRestockKale,
    shopperId: ids.shoppers.jordan,
    storeId: ids.stores.eastEndOrganic,
    itemId: ids.items.kale,
    type: "item_restock" as const,
    isActive: true,
    createdAt: atHours(-4),
  },
  {
    id: ids.alerts.alexFollowThreeRivers,
    shopperId: ids.shoppers.shopper03,
    storeId: ids.stores.threeRivers,
    itemId: null,
    type: "store_follow" as const,
    isActive: true,
    createdAt: atDays(-6),
  },
  {
    id: ids.alerts.taylorFollowRiverHalal,
    shopperId: ids.shoppers.shopper04,
    storeId: ids.stores.riverHalalHub,
    itemId: null,
    type: "store_follow" as const,
    isActive: true,
    createdAt: atDays(-4),
  },
  {
    id: ids.alerts.samFollowLotus,
    shopperId: ids.shoppers.shopper05,
    storeId: ids.stores.lotus,
    itemId: null,
    type: "store_follow" as const,
    isActive: true,
    createdAt: atDays(-3),
  },
  {
    id: ids.alerts.morganFollowEastEnd,
    shopperId: ids.shoppers.shopper07,
    storeId: ids.stores.eastEndOrganic,
    itemId: null,
    type: "store_follow" as const,
    isActive: true,
    createdAt: atDays(-5),
  },
  {
    id: ids.alerts.rileyFollowTokyo,
    shopperId: ids.shoppers.shopper06,
    storeId: ids.stores.tokyoMart,
    itemId: null,
    type: "store_follow" as const,
    isActive: true,
    createdAt: atDays(-2),
  },
  {
    id: ids.alerts.cameronFollowPress,
    shopperId: ids.shoppers.shopper11,
    storeId: ids.stores.pressJuice,
    itemId: null,
    type: "store_follow" as const,
    isActive: true,
    createdAt: atDays(-1),
  },
  {
    id: ids.alerts.drewRestockChicken,
    shopperId: ids.shoppers.shopper09,
    storeId: ids.stores.crescent,
    itemId: ids.items.halalChickenBreast,
    type: "item_restock" as const,
    isActive: true,
    createdAt: atHours(-30),
  },
];

export const storeRatings = [
  {
    id: ids.ratings.ninaLotus,
    storeId: ids.stores.lotus,
    shopperId: ids.shoppers.nina,
    score: 5,
    note: "Great selection of fresh produce and a really friendly team. The bok choy is always crisp.",
    createdAt: atDays(-3),
    updatedAt: atDays(-3),
  },
  {
    id: ids.ratings.ninaCrescent,
    storeId: ids.stores.crescent,
    shopperId: ids.shoppers.nina,
    score: 4,
    note: "Best halal meat selection I've found in the South Side area. Fair prices.",
    createdAt: atDays(-2),
    updatedAt: atDays(-2),
  },
  {
    id: ids.ratings.jordanTokyo,
    storeId: ids.stores.tokyoMart,
    shopperId: ids.shoppers.jordan,
    score: 5,
    note: "Best spot in Pittsburgh for Korean and Japanese pantry staples. Always well-stocked.",
    createdAt: atDays(-4),
    updatedAt: atDays(-4),
  },
  {
    id: ids.ratings.jordanEastEnd,
    storeId: ids.stores.eastEndOrganic,
    shopperId: ids.shoppers.jordan,
    score: 4,
    note: "Love the sourdough and the local produce. Parking can be tricky on weekends.",
    createdAt: atDays(-3),
    updatedAt: atDays(-3),
  },
  {
    id: ids.ratings.alexThreeRivers,
    storeId: ids.stores.threeRivers,
    shopperId: ids.shoppers.shopper03,
    score: 5,
    note: "Excellent organic selection, everything feels genuinely farm-fresh.",
    createdAt: atDays(-5),
    updatedAt: atDays(-5),
  },
  {
    id: ids.ratings.taylorRiverHalal,
    storeId: ids.stores.riverHalalHub,
    shopperId: ids.shoppers.shopper04,
    score: 4,
    note: "Good variety of halal meats and the dates are always top quality.",
    createdAt: atDays(-2),
    updatedAt: atDays(-2),
  },
  {
    id: ids.ratings.samLotus,
    storeId: ids.stores.lotus,
    shopperId: ids.shoppers.shopper05,
    score: 4,
    note: "Fresh vegetables and a great Asian pantry section. Wish they were open a bit later.",
    createdAt: atDays(-6),
    updatedAt: atDays(-6),
  },
  {
    id: ids.ratings.morganEastEnd,
    storeId: ids.stores.eastEndOrganic,
    shopperId: ids.shoppers.shopper07,
    score: 5,
    note: "My go-to for organic staples in East Liberty. The kale is always harvested fresh.",
    createdAt: atDays(-1),
    updatedAt: atDays(-1),
  },
  // -----------------------------------------------------------------------
  // Additional ratings — more shoppers across all stores
  // -----------------------------------------------------------------------
  {
    id: ids.ratings.rileyLotus,
    storeId: ids.stores.lotus,
    shopperId: ids.shoppers.shopper06,
    score: 4,
    note: "Consistently fresh produce and a great pantry section. The galbi and bok choy are always top quality.",
    createdAt: atDays(-2),
    updatedAt: atDays(-2),
  },
  {
    id: ids.ratings.drewLotus,
    storeId: ids.stores.lotus,
    shopperId: ids.shoppers.shopper09,
    score: 5,
    note: "Best Asian grocery in Pittsburgh. Friendly staff and everything is always well stocked.",
    createdAt: atDays(-4),
    updatedAt: atDays(-4),
  },
  {
    id: ids.ratings.samCrescent,
    storeId: ids.stores.crescent,
    shopperId: ids.shoppers.shopper05,
    score: 5,
    note: "Halal selection is excellent — fresh lamb every time. Wouldn't shop anywhere else for halal cuts.",
    createdAt: atDays(-3),
    updatedAt: atDays(-3),
  },
  {
    id: ids.ratings.cameronCrescent,
    storeId: ids.stores.crescent,
    shopperId: ids.shoppers.shopper11,
    score: 4,
    note: "Really reliable halal source in the South Side. The pita is always fresh and the chickpeas are a great deal.",
    createdAt: atDays(-5),
    updatedAt: atDays(-5),
  },
  {
    id: ids.ratings.rileyThreeRivers,
    storeId: ids.stores.threeRivers,
    shopperId: ids.shoppers.shopper06,
    score: 4,
    note: "Love the commitment to local sourcing. The eggs are always from nearby farms and the produce is genuinely fresh.",
    createdAt: atDays(-3),
    updatedAt: atDays(-3),
  },
  {
    id: ids.ratings.jordanThreeRivers,
    storeId: ids.stores.threeRivers,
    shopperId: ids.shoppers.jordan,
    score: 5,
    note: "My favorite organic grocer in Pittsburgh. The heirloom tomatoes and rainbow carrots are worth the trip.",
    createdAt: atDays(-2),
    updatedAt: atDays(-2),
  },
  {
    id: ids.ratings.ninaTokyoMart,
    storeId: ids.stores.tokyoMart,
    shopperId: ids.shoppers.nina,
    score: 4,
    note: "Great selection of Japanese and Korean staples. The house kimchi is a must-try and the fresh udon is excellent.",
    createdAt: atDays(-3),
    updatedAt: atDays(-3),
  },
  {
    id: ids.ratings.alexTokyoMart,
    storeId: ids.stores.tokyoMart,
    shopperId: ids.shoppers.shopper03,
    score: 5,
    note: "I drive from Oakland just for the fresh udon and the Japanese pantry section. Nothing else in Pittsburgh comes close.",
    createdAt: atDays(-6),
    updatedAt: atDays(-6),
  },
  {
    id: ids.ratings.samRiverHalal,
    storeId: ids.stores.riverHalalHub,
    shopperId: ids.shoppers.shopper05,
    score: 4,
    note: "Friendly staff and always fresh halal cuts. The goat is especially good and the dates are always premium quality.",
    createdAt: atDays(-4),
    updatedAt: atDays(-4),
  },
  {
    id: ids.ratings.cameronRiverHalal,
    storeId: ids.stores.riverHalalHub,
    shopperId: ids.shoppers.shopper11,
    score: 5,
    note: "Best place to shop for Ramadan — dates, goat, lamb, all top quality and halal certified. Very knowledgeable staff.",
    createdAt: atDays(-2),
    updatedAt: atDays(-2),
  },
  {
    id: ids.ratings.drewEastEnd,
    storeId: ids.stores.eastEndOrganic,
    shopperId: ids.shoppers.shopper09,
    score: 5,
    note: "The sourdough is incredible and the local honey is the best I've found. A real neighborhood gem.",
    createdAt: atDays(-3),
    updatedAt: atDays(-3),
  },
  // -----------------------------------------------------------------------
  // The Press Juice Co.
  // -----------------------------------------------------------------------
  {
    id: ids.ratings.ninaPressJuice,
    storeId: ids.stores.pressJuice,
    shopperId: ids.shoppers.nina,
    score: 5,
    note: "The honeycrisp cider is unreal. I come every week without fail. Best pressed juice spot in Pittsburgh.",
    createdAt: atDays(-2),
    updatedAt: atDays(-2),
  },
  {
    id: ids.ratings.taylorPressJuice,
    storeId: ids.stores.pressJuice,
    shopperId: ids.shoppers.shopper04,
    score: 4,
    note: "Fresh pressed and actually delicious — nothing like the commercial stuff. The watermelon mint is refreshing.",
    createdAt: atDays(-4),
    updatedAt: atDays(-4),
  },
  {
    id: ids.ratings.jordanPressJuice,
    storeId: ids.stores.pressJuice,
    shopperId: ids.shoppers.jordan,
    score: 5,
    note: "The apple juice is pressed on-site, you can literally taste the difference. Watermelon mint is my go-to in summer.",
    createdAt: atDays(-1),
    updatedAt: atDays(-1),
  },
  {
    id: ids.ratings.cameronPressJuice,
    storeId: ids.stores.pressJuice,
    shopperId: ids.shoppers.shopper11,
    score: 4,
    note: "Really quality juices with interesting seasonal flavors. The green detox is surprisingly good.",
    createdAt: atDays(-5),
    updatedAt: atDays(-5),
  },
];

const PRESS_SEARCH_QUERIES = [
  "apple",
  "apple juice",
  "juice",
  "cider",
  "gallon",
  "organic",
  "honeycrisp",
  "press",
];

const LOTUS_SEARCH_QUERIES = [
  "bok choy",
  "ramen",
  "noodles",
  "spinach",
  "bok choi",
];

const TOKYO_SEARCH_QUERIES = [
  "gochujang",
  "napa cabbage",
  "kimchi",
  "korean chili",
  "miso",
];

export const storeProfileViewsSeed = [
  ...Array.from({ length: 25 }, (_, i) => ({
    storeId: ids.stores.lotus,
    createdAt: atHours(-i * 22 - 2),
  })),
  ...Array.from({ length: 20 }, (_, i) => ({
    storeId: ids.stores.crescent,
    createdAt: atHours(-i * 27 - 3),
  })),
  ...Array.from({ length: 17 }, (_, i) => ({
    storeId: ids.stores.threeRivers,
    createdAt: atHours(-i * 31 - 7),
  })),
  ...Array.from({ length: 22 }, (_, i) => ({
    storeId: ids.stores.tokyoMart,
    createdAt: atHours(-i * 25 - 5),
  })),
  ...Array.from({ length: 14 }, (_, i) => ({
    storeId: ids.stores.riverHalalHub,
    createdAt: atHours(-i * 37 - 4),
  })),
  ...Array.from({ length: 19 }, (_, i) => ({
    storeId: ids.stores.eastEndOrganic,
    createdAt: atHours(-i * 29 - 6),
  })),
  ...Array.from({ length: 38 }, (_, i) => ({
    storeId: ids.stores.pressJuice,
    createdAt: atHours(-i * 19 - 1),
  })),
];

export const storeItemSearchesSeed = [
  ...Array.from({ length: 22 }, (_, i) => ({
    storeId: ids.stores.pressJuice,
    query: PRESS_SEARCH_QUERIES[i % PRESS_SEARCH_QUERIES.length],
    createdAt: atHours(-i * 31 - 4),
  })),
  ...Array.from({ length: 12 }, (_, i) => ({
    storeId: ids.stores.lotus,
    query: LOTUS_SEARCH_QUERIES[i % LOTUS_SEARCH_QUERIES.length],
    createdAt: atHours(-i * 41 - 6),
  })),
  ...Array.from({ length: 10 }, (_, i) => ({
    storeId: ids.stores.tokyoMart,
    query: TOKYO_SEARCH_QUERIES[i % TOKYO_SEARCH_QUERIES.length],
    createdAt: atHours(-i * 47 - 8),
  })),
];
